"""
Draft vs Live diff for the canonical (document-normalized) policy
pipeline — extension of PR #4 which covered the compensation matrix.

Background
  Two parallel pipelines publish policy to employees today:

    * Compensation matrix — policy_config_versions + policy_config_benefits.
      Diff shipped in policy_config_matrix_service.compute_diff (PR #4).

    * Canonical document-normalized — company_policies → policy_versions
      with policy_benefit_rules + policy_exclusions. This module covers
      that side of the house so HR gets the same "what changed?" preview
      before publishing a normalized-from-document version.

Scope deliberately narrower than the matrix diff:
  * Compares benefit rules + exclusions (the two tables HR actually
    publishes to employees). policy_rule_conditions and
    policy_evidence_requirements are left out of this first cut — HR
    rarely edits them directly, and showing them in the diff would
    clutter the view. A follow-up can extend if needed.
  * No revert-row action yet (the matrix has one). Canonical rules are
    usually regenerated by re-normalizing a document, so a per-row
    revert has fuzzier semantics and deserves its own product round.

Row identity
  * Benefit rule: (benefit_key, calc_type, amount_unit, frequency).
    Dimensionally stable across re-normalizations; rules with the same
    tuple but different amount_value become "changed". Ties (two rules
    sharing the tuple) pair positionally by (amount_value, description).
  * Exclusion: (benefit_key or '', domain). Two exclusions sharing this
    tuple pair positionally by description.

Both use json-stable string comparison for dict/JSON fields so
dict-key ordering doesn't produce false "changed" entries.
"""
from __future__ import annotations

import json
from typing import Any, Dict, List, Optional, Tuple


_RULE_COMPARE_FIELDS: Tuple[str, ...] = (
    "benefit_category",
    "amount_value",
    "currency",
    "description",
    "raw_text",
    "review_status",
    "confidence",
    "metadata_json",
)

_EXCLUSION_COMPARE_FIELDS: Tuple[str, ...] = (
    "description",
    "raw_text",
    "review_status",
    "confidence",
)


def _rule_id(rule: Dict[str, Any]) -> Tuple[str, str, str, str]:
    return (
        str(rule.get("benefit_key") or ""),
        str(rule.get("calc_type") or ""),
        str(rule.get("amount_unit") or ""),
        str(rule.get("frequency") or ""),
    )


def _exclusion_id(excl: Dict[str, Any]) -> Tuple[str, str]:
    return (
        str(excl.get("benefit_key") or ""),
        str(excl.get("domain") or ""),
    )


def _rule_field_changes(live: Dict[str, Any], draft: Dict[str, Any]) -> List[str]:
    out: List[str] = []
    for f in _RULE_COMPARE_FIELDS:
        lv = live.get(f)
        dv = draft.get(f)
        if isinstance(lv, dict) or isinstance(dv, dict):
            ls = json.dumps(lv or {}, sort_keys=True)
            ds = json.dumps(dv or {}, sort_keys=True)
            if ls != ds:
                out.append(f)
            continue
        if (lv or None) != (dv or None):
            out.append(f)
    return out


def _exclusion_field_changes(live: Dict[str, Any], draft: Dict[str, Any]) -> List[str]:
    out: List[str] = []
    for f in _EXCLUSION_COMPARE_FIELDS:
        lv = live.get(f)
        dv = draft.get(f)
        if (lv or None) != (dv or None):
            out.append(f)
    return out


def _pair_by_identity(
    live_rows: List[Dict[str, Any]],
    draft_rows: List[Dict[str, Any]],
    identity_fn,
):
    """
    Pair rows by identity. Returns (added, removed, paired) where
    paired is a list of (live, draft) tuples. Ties (multiple rows
    sharing an identity within a version) pair positionally in
    insertion order.
    """
    from collections import defaultdict

    live_by_id: Dict[Any, List[Dict[str, Any]]] = defaultdict(list)
    for r in live_rows:
        live_by_id[identity_fn(r)].append(r)
    draft_by_id: Dict[Any, List[Dict[str, Any]]] = defaultdict(list)
    for r in draft_rows:
        draft_by_id[identity_fn(r)].append(r)

    added: List[Dict[str, Any]] = []
    removed: List[Dict[str, Any]] = []
    paired: List[Tuple[Dict[str, Any], Dict[str, Any]]] = []

    all_keys = set(live_by_id) | set(draft_by_id)
    for k in sorted(all_keys, key=lambda x: tuple(str(v) for v in x)):
        l = live_by_id.get(k, [])
        d = draft_by_id.get(k, [])
        # Pair positionally
        for idx in range(max(len(l), len(d))):
            lv = l[idx] if idx < len(l) else None
            dv = d[idx] if idx < len(d) else None
            if lv is None and dv is not None:
                added.append(dv)
            elif dv is None and lv is not None:
                removed.append(lv)
            elif lv is not None and dv is not None:
                paired.append((lv, dv))
    return added, removed, paired


def _sanitize_rule(row: Optional[Dict[str, Any]]) -> Optional[Dict[str, Any]]:
    """Strip internal-only fields (ids, timestamps) for the API payload."""
    if row is None:
        return None
    return {
        "benefit_key": row.get("benefit_key"),
        "benefit_category": row.get("benefit_category"),
        "calc_type": row.get("calc_type"),
        "amount_value": row.get("amount_value"),
        "amount_unit": row.get("amount_unit"),
        "currency": row.get("currency"),
        "frequency": row.get("frequency"),
        "description": row.get("description"),
        "raw_text": row.get("raw_text"),
        "review_status": row.get("review_status"),
        "confidence": row.get("confidence"),
        "metadata_json": row.get("metadata_json"),
    }


def _sanitize_exclusion(row: Optional[Dict[str, Any]]) -> Optional[Dict[str, Any]]:
    if row is None:
        return None
    return {
        "benefit_key": row.get("benefit_key"),
        "domain": row.get("domain"),
        "description": row.get("description"),
        "raw_text": row.get("raw_text"),
        "review_status": row.get("review_status"),
        "confidence": row.get("confidence"),
    }


def _version_meta(v: Optional[Dict[str, Any]]) -> Optional[Dict[str, Any]]:
    if not v:
        return None
    return {
        "id": str(v.get("id")) if v.get("id") else None,
        "version_number": int(v.get("version_number") or 0),
        "status": str(v.get("status") or ""),
        "review_status": v.get("review_status"),
        "confidence": v.get("confidence"),
        "created_at": v.get("created_at"),
        "updated_at": v.get("updated_at"),
    }


def _load_draft_version(db: Any, policy_id: str) -> Optional[Dict[str, Any]]:
    """Return the most recent draft/review_required policy_version for the policy, if any."""
    from sqlalchemy import text  # local import keeps service importable without DB

    with db.engine.connect() as conn:
        row = conn.execute(
            text(
                """
                SELECT * FROM policy_versions
                WHERE policy_id = :pid
                  AND status IN ('draft', 'review_required', 'reviewed')
                ORDER BY version_number DESC, created_at DESC
                LIMIT 1
                """
            ),
            {"pid": str(policy_id)},
        ).fetchone()
    if row is None:
        return None
    d = db._row_to_dict(row)
    try:
        db._decode_policy_version_row(d)
    except Exception:
        pass
    return d


def compute_canonical_diff(db: Any, policy_id: str) -> Dict[str, Any]:
    """
    Snapshot of {live, draft, diff} for a canonical company_policy.

    The response shape intentionally mirrors the matrix diff so the
    frontend can render both with the same mental model:

      {
        "live":   {"version": {...} | None, "rules": [...], "exclusions": [...]},
        "draft":  {"version": {...} | None, "rules": [...], "exclusions": [...]},
        "diff": {
          "rules":      {"added": [...], "removed": [...],
                         "changed": [{"before": ..., "after": ...,
                                      "changed_fields": [...]}],
                         "unchanged_count": int},
          "exclusions": {"added": [...], "removed": [...],
                         "changed": [...],
                         "unchanged_count": int},
          "summary": {"rules": {...}, "exclusions": {...}}
        }
      }

    If neither a draft nor a live version exists, returns the empty
    shape with zero counts and version=None. Caller decides how to
    render the empty state.
    """
    live = db.get_published_policy_version(str(policy_id))
    draft = _load_draft_version(db, str(policy_id))

    live_rules: List[Dict[str, Any]] = []
    live_excl: List[Dict[str, Any]] = []
    draft_rules: List[Dict[str, Any]] = []
    draft_excl: List[Dict[str, Any]] = []
    if live:
        live_rules = db.list_policy_benefit_rules(str(live["id"]))
        live_excl = db.list_policy_exclusions(str(live["id"]))
    if draft:
        draft_rules = db.list_policy_benefit_rules(str(draft["id"]))
        draft_excl = db.list_policy_exclusions(str(draft["id"]))

    # --- rules -------------------------------------------------------
    added_r, removed_r, paired_r = _pair_by_identity(
        live_rules, draft_rules, _rule_id
    )
    changed_r: List[Dict[str, Any]] = []
    unchanged_r_count = 0
    for lv, dv in paired_r:
        fields = _rule_field_changes(lv, dv)
        if fields:
            changed_r.append(
                {
                    "before": _sanitize_rule(lv),
                    "after": _sanitize_rule(dv),
                    "changed_fields": fields,
                }
            )
        else:
            unchanged_r_count += 1

    # --- exclusions --------------------------------------------------
    added_e, removed_e, paired_e = _pair_by_identity(
        live_excl, draft_excl, _exclusion_id
    )
    changed_e: List[Dict[str, Any]] = []
    unchanged_e_count = 0
    for lv, dv in paired_e:
        fields = _exclusion_field_changes(lv, dv)
        if fields:
            changed_e.append(
                {
                    "before": _sanitize_exclusion(lv),
                    "after": _sanitize_exclusion(dv),
                    "changed_fields": fields,
                }
            )
        else:
            unchanged_e_count += 1

    return {
        "live": {
            "version": _version_meta(live),
            "rules": [_sanitize_rule(r) for r in live_rules],
            "exclusions": [_sanitize_exclusion(r) for r in live_excl],
        },
        "draft": {
            "version": _version_meta(draft),
            "rules": [_sanitize_rule(r) for r in draft_rules],
            "exclusions": [_sanitize_exclusion(r) for r in draft_excl],
        },
        "diff": {
            "rules": {
                "added": [_sanitize_rule(r) for r in added_r],
                "removed": [_sanitize_rule(r) for r in removed_r],
                "changed": changed_r,
                "unchanged_count": unchanged_r_count,
            },
            "exclusions": {
                "added": [_sanitize_exclusion(r) for r in added_e],
                "removed": [_sanitize_exclusion(r) for r in removed_e],
                "changed": changed_e,
                "unchanged_count": unchanged_e_count,
            },
            "summary": {
                "rules": {
                    "added": len(added_r),
                    "removed": len(removed_r),
                    "changed": len(changed_r),
                    "unchanged": unchanged_r_count,
                },
                "exclusions": {
                    "added": len(added_e),
                    "removed": len(removed_e),
                    "changed": len(changed_e),
                    "unchanged": unchanged_e_count,
                },
            },
        },
    }


def resolve_primary_policy_id_for_company(db: Any, company_id: str) -> Optional[str]:
    """
    Return the most recently created company_policy id for a given
    company, or None. Used by the /api/hr/canonical-policy/diff helper
    endpoint so the frontend doesn't need a separate lookup.
    """
    row = db.get_latest_company_policy(str(company_id))
    if not row:
        return None
    pid = row.get("id")
    return str(pid) if pid else None
