from typing import List, Dict, Any


HOUSING_SEED: List[Dict[str, Any]] = [
    {
        "id": "h1",
        "name": "Oakwood Residence Orchard",
        "area": "Tanglin",
        "bedrooms": 3,
        "furnished": True,
        "nearMRT": True,
        "estMonthlySGDMin": 7000,
        "estMonthlySGDMax": 9000,
        "familyFriendlyScore": 9,
        "notes": "Serviced apartment with pool, gym, and kids' club. Walking distance to international schools.",
    },
    {
        "id": "h2",
        "name": "Somerset Grand Cairnhill",
        "area": "River Valley",
        "bedrooms": 3,
        "furnished": True,
        "nearMRT": True,
        "estMonthlySGDMin": 6500,
        "estMonthlySGDMax": 8500,
        "familyFriendlyScore": 8,
        "notes": "Central location with easy access to Orchard Road. Pool and playground on-site.",
    },
    {
        "id": "h3",
        "name": "The Residence at Holland V",
        "area": "Holland Village",
        "bedrooms": 4,
        "furnished": True,
        "nearMRT": True,
        "estMonthlySGDMin": 8000,
        "estMonthlySGDMax": 10000,
        "familyFriendlyScore": 10,
        "notes": "Large family apartments in expat-friendly neighborhood. Close to several international schools.",
    },
    {
        "id": "h4",
        "name": "Citadines Rochor",
        "area": "Novena",
        "bedrooms": 3,
        "furnished": True,
        "nearMRT": True,
        "estMonthlySGDMin": 5000,
        "estMonthlySGDMax": 6500,
        "familyFriendlyScore": 7,
        "notes": "Value-for-money serviced apartment near medical district and MRT.",
    },
    {
        "id": "h5",
        "name": "Ascott Raffles Place",
        "area": "River Valley",
        "bedrooms": 3,
        "furnished": True,
        "nearMRT": True,
        "estMonthlySGDMin": 7500,
        "estMonthlySGDMax": 9500,
        "familyFriendlyScore": 8,
        "notes": "Central location with rooftop facilities. Short-term leases available.",
    },
    {
        "id": "h6",
        "name": "Botannia Apartments",
        "area": "Bukit Timah",
        "bedrooms": 4,
        "furnished": True,
        "nearMRT": False,
        "estMonthlySGDMin": 9000,
        "estMonthlySGDMax": 11000,
        "familyFriendlyScore": 9,
        "notes": "Spacious low-rise apartments near nature reserves. Popular with expat families.",
    },
    {
        "id": "h7",
        "name": "Marine Parade Suites",
        "area": "East Coast",
        "bedrooms": 3,
        "furnished": True,
        "nearMRT": False,
        "estMonthlySGDMin": 5500,
        "estMonthlySGDMax": 7000,
        "familyFriendlyScore": 9,
        "notes": "Beachfront location with relaxed vibe. Great for families who love outdoor activities.",
    },
    {
        "id": "h8",
        "name": "Tiong Bahru Heights",
        "area": "Tiong Bahru",
        "bedrooms": 3,
        "furnished": True,
        "nearMRT": True,
        "estMonthlySGDMin": 6000,
        "estMonthlySGDMax": 7500,
        "familyFriendlyScore": 8,
        "notes": "Trendy neighborhood with great cafes and food. Mix of local and expat community.",
    },
    {
        "id": "h9",
        "name": "Novena Suites",
        "area": "Novena",
        "bedrooms": 4,
        "furnished": True,
        "nearMRT": True,
        "estMonthlySGDMin": 7000,
        "estMonthlySGDMax": 8500,
        "familyFriendlyScore": 8,
        "notes": "Modern development with excellent facilities. Close to schools and shopping.",
    },
    {
        "id": "h10",
        "name": "Tanglin Hill Residences",
        "area": "Tanglin",
        "bedrooms": 4,
        "furnished": True,
        "nearMRT": False,
        "estMonthlySGDMin": 10000,
        "estMonthlySGDMax": 13000,
        "familyFriendlyScore": 10,
        "notes": "Premium serviced apartments in embassy district. Top choice for expat executives.",
    },
]


SCHOOLS_SEED: List[Dict[str, Any]] = [
    {
        "id": "s1",
        "name": "Tanglin Trust School",
        "area": "Tanglin",
        "curriculumTags": ["UK", "IB"],
        "ageRange": "3-18",
        "estAnnualSGDMin": 38000,
        "estAnnualSGDMax": 45000,
        "languageSupport": ["English", "Mandarin", "Spanish"],
        "notes": "Highly regarded British international school with strong academic reputation.",
    },
    {
        "id": "s2",
        "name": "United World College of South East Asia (UWCSEA)",
        "area": "Dover/East Coast",
        "curriculumTags": ["IB"],
        "ageRange": "3-18",
        "estAnnualSGDMin": 35000,
        "estAnnualSGDMax": 42000,
        "languageSupport": ["English", "Mandarin", "French"],
        "notes": "IB-focused school with strong community values. Two campuses (Dover and East).",
    },
    {
        "id": "s3",
        "name": "Singapore American School (SAS)",
        "area": "Woodlands",
        "curriculumTags": ["US", "IB"],
        "ageRange": "3-18",
        "estAnnualSGDMin": 36000,
        "estAnnualSGDMax": 43000,
        "languageSupport": ["English", "Mandarin"],
        "notes": "American curriculum with IB option. Large campus with excellent facilities.",
    },
    {
        "id": "s4",
        "name": "Australian International School (AIS)",
        "area": "Lorong Chuan",
        "curriculumTags": ["IB", "Australian"],
        "ageRange": "3-18",
        "estAnnualSGDMin": 30000,
        "estAnnualSGDMax": 38000,
        "languageSupport": ["English"],
        "notes": "Balanced curriculum with strong sports and arts programs.",
    },
    {
        "id": "s5",
        "name": "Dulwich College Singapore",
        "area": "Bukit Timah",
        "curriculumTags": ["UK", "IB"],
        "ageRange": "2-18",
        "estAnnualSGDMin": 32000,
        "estAnnualSGDMax": 40000,
        "languageSupport": ["English", "Mandarin"],
        "notes": "British curriculum with strong emphasis on performing arts.",
    },
    {
        "id": "s6",
        "name": "Canadian International School (CIS)",
        "area": "Tanjong Katong/Lakeside",
        "curriculumTags": ["IB", "Canadian"],
        "ageRange": "2-18",
        "estAnnualSGDMin": 28000,
        "estAnnualSGDMax": 36000,
        "languageSupport": ["English", "French", "Mandarin"],
        "notes": "Bilingual program option and strong language support.",
    },
    {
        "id": "s7",
        "name": "Overseas Family School (OFS)",
        "area": "Pasir Ris",
        "curriculumTags": ["IB"],
        "ageRange": "3-18",
        "estAnnualSGDMin": 25000,
        "estAnnualSGDMax": 32000,
        "languageSupport": ["English", "Mandarin", "Spanish"],
        "notes": "Inclusive school with strong ESL support. Good value for money.",
    },
    {
        "id": "s8",
        "name": "Nexus International School",
        "area": "Aljunied",
        "curriculumTags": ["IB"],
        "ageRange": "3-18",
        "estAnnualSGDMin": 27000,
        "estAnnualSGDMax": 34000,
        "languageSupport": ["English", "Mandarin"],
        "notes": "Growing school with modern facilities and strong STEM focus.",
    },
    {
        "id": "s9",
        "name": "XCL World Academy",
        "area": "Yishun",
        "curriculumTags": ["IB"],
        "ageRange": "2-18",
        "estAnnualSGDMin": 30000,
        "estAnnualSGDMax": 38000,
        "languageSupport": ["English", "Mandarin", "French"],
        "notes": "Inquiry-based learning with excellent facilities.",
    },
    {
        "id": "s10",
        "name": "Dover Court International School",
        "area": "Dover",
        "curriculumTags": ["UK", "IB"],
        "ageRange": "3-18",
        "estAnnualSGDMin": 29000,
        "estAnnualSGDMax": 37000,
        "languageSupport": ["English"],
        "notes": "British curriculum with welcoming community. Strong pastoral care.",
    },
]


MOVERS_SEED: List[Dict[str, Any]] = [
    {
        "id": "m1",
        "name": "Asian Tigers Mobility",
        "serviceTags": ["Full service", "Storage", "Pet relocation", "Insurance"],
        "notes": "Leading international mover in Asia. Premium service with white-glove handling.",
        "rfqTemplate": "Request quote for Oslo → Singapore, {inventory_size} household, {special_items_count} special items. Arrival: {arrival_date}.",
    },
    {
        "id": "m2",
        "name": "Crown Relocations",
        "serviceTags": ["Full service", "Storage", "Insurance", "Orientation services"],
        "notes": "Global mobility specialist. Includes destination services and settling-in support.",
        "rfqTemplate": "Request quote for Oslo → Singapore, {inventory_size} household, {special_items_count} special items. Arrival: {arrival_date}.",
    },
    {
        "id": "m3",
        "name": "Santa Fe Relocation",
        "serviceTags": ["Full service", "Storage", "Vehicle shipping"],
        "notes": "Established mover with strong Norway-Singapore route experience.",
        "rfqTemplate": "Request quote for Oslo → Singapore, {inventory_size} household, {special_items_count} special items. Arrival: {arrival_date}.",
    },
    {
        "id": "m4",
        "name": "Allied Pickfords",
        "serviceTags": ["Full service", "Insurance", "Value option"],
        "notes": "Good value international mover with reliable service.",
        "rfqTemplate": "Request quote for Oslo → Singapore, {inventory_size} household, {special_items_count} special items. Arrival: {arrival_date}.",
    },
    {
        "id": "m5",
        "name": "AGS Movers Singapore",
        "serviceTags": ["Full service", "Storage", "Pet relocation"],
        "notes": "Family-owned business with personalized service. Strong European connections.",
        "rfqTemplate": "Request quote for Oslo → Singapore, {inventory_size} household, {special_items_count} special items. Arrival: {arrival_date}.",
    },
]


def get_housing_seed() -> List[Dict[str, Any]]:
    return HOUSING_SEED


def get_schools_seed() -> List[Dict[str, Any]]:
    return SCHOOLS_SEED


def get_movers_seed() -> List[Dict[str, Any]]:
    return MOVERS_SEED
