import { generatePath } from 'react-router-dom';

export type RouteRole = 'PUBLIC' | 'HR' | 'EMPLOYEE' | 'ADMIN';

export const ROUTE_DEFS = {
  landing: { path: '/', roles: ['PUBLIC'] as RouteRole[] },
  auth: { path: '/auth', roles: ['PUBLIC'] as RouteRole[] },
  employeeJourney: { path: '/employee/journey', roles: ['EMPLOYEE', 'ADMIN'] as RouteRole[] },
  employeeDashboard: { path: '/employee/dashboard', roles: ['EMPLOYEE', 'ADMIN'] as RouteRole[] },
  hrDashboard: { path: '/hr/dashboard', roles: ['HR', 'ADMIN'] as RouteRole[] },
  hrCommandCenter: { path: '/hr/command-center', roles: ['HR', 'ADMIN'] as RouteRole[] },
  hrCommandCenterCase: { path: '/hr/command-center/cases/:id', roles: ['HR', 'ADMIN'] as RouteRole[] },
  hrEmployeeDashboard: { path: '/hr/employee-dashboard', roles: ['HR', 'ADMIN'] as RouteRole[] },
  hrCaseSummary: { path: '/hr/cases/:caseId', roles: ['HR', 'ADMIN'] as RouteRole[] },
  hrReview: { path: '/hr/review', roles: ['HR', 'ADMIN'] as RouteRole[] },
  hrReviewCase: { path: '/hr/review/case/:caseId', roles: ['HR', 'ADMIN'] as RouteRole[] },
  hrAssignmentReview: { path: '/hr/assignments/:id', roles: ['HR', 'ADMIN'] as RouteRole[] },
  hrComplianceIndex: { path: '/hr/compliance', roles: ['HR', 'ADMIN'] as RouteRole[] },
  hrCompliance: { path: '/hr/compliance/:id', roles: ['HR', 'ADMIN'] as RouteRole[] },
  hrPackage: { path: '/hr/package/:id', roles: ['HR', 'ADMIN'] as RouteRole[] },
  auditNavigation: { path: '/audit/navigation', roles: ['HR', 'EMPLOYEE', 'ADMIN'] as RouteRole[] },
  providers: { path: '/providers', roles: ['HR', 'EMPLOYEE', 'ADMIN'] as RouteRole[] },
  services: { path: '/services', roles: ['HR', 'EMPLOYEE', 'ADMIN'] as RouteRole[] },
  servicesQuestions: { path: '/services/questions', roles: ['HR', 'EMPLOYEE', 'ADMIN'] as RouteRole[] },
  servicesRecommendations: { path: '/services/recommendations', roles: ['HR', 'EMPLOYEE', 'ADMIN'] as RouteRole[] },
  servicesEstimate: { path: '/services/estimate', roles: ['HR', 'EMPLOYEE', 'ADMIN'] as RouteRole[] },
  servicesRfqNew: { path: '/services/rfq/new', roles: ['HR', 'EMPLOYEE', 'ADMIN'] as RouteRole[] },
  servicesConclusion: { path: '/services/conclusion', roles: ['HR', 'EMPLOYEE', 'ADMIN'] as RouteRole[] },
  quotesInbox: { path: '/quotes', roles: ['HR', 'EMPLOYEE', 'ADMIN'] as RouteRole[] },
  quoteRfqDetail: { path: '/quotes/rfq/:rfqId', roles: ['HR', 'EMPLOYEE', 'ADMIN'] as RouteRole[] },
  vendorInbox: { path: '/vendor/inbox', roles: ['ADMIN', 'EMPLOYEE', 'HR'] as RouteRole[] },
  vendorRfq: { path: '/vendor/rfq/:id', roles: ['ADMIN', 'EMPLOYEE', 'HR'] as RouteRole[] },
  messages: { path: '/messages', roles: ['HR', 'EMPLOYEE', 'ADMIN'] as RouteRole[] },
  resources: { path: '/resources', roles: ['HR', 'EMPLOYEE', 'ADMIN'] as RouteRole[] },
  caseResources: { path: '/cases/:caseId/resources', roles: ['HR', 'EMPLOYEE', 'ADMIN'] as RouteRole[] },
  hrMessages: { path: '/hr/messages', roles: ['HR', 'ADMIN'] as RouteRole[] },
  hrResources: { path: '/hr/resources', roles: ['HR', 'ADMIN'] as RouteRole[] },
  hrPreferredSuppliers: { path: '/hr/preferred-suppliers', roles: ['HR', 'ADMIN'] as RouteRole[] },
  hrPolicy: { path: '/hr/policy', roles: ['HR', 'EMPLOYEE', 'ADMIN'] as RouteRole[] },
  employeeHrPolicy: { path: '/employee/hr-policy', roles: ['EMPLOYEE', 'ADMIN'] as RouteRole[] },
  hrPolicyManagement: { path: '/hr/policy-management', roles: ['HR', 'ADMIN'] as RouteRole[] },
  submissionCenter: { path: '/submission-center', roles: ['HR', 'ADMIN'] as RouteRole[] },
  hrCompanyProfile: { path: '/hr/company-profile', roles: ['HR', 'ADMIN'] as RouteRole[] },
  notificationSettings: { path: '/settings/notifications', roles: ['HR', 'EMPLOYEE', 'ADMIN'] as RouteRole[] },
  adminConsole: { path: '/admin', roles: ['ADMIN'] as RouteRole[] },
  adminCompanies: { path: '/admin/companies', roles: ['ADMIN'] as RouteRole[] },
  adminResearch: { path: '/admin/research', roles: ['ADMIN'] as RouteRole[] },
  adminUsers: { path: '/admin/users', roles: ['ADMIN'] as RouteRole[] },
  adminRelocations: { path: '/admin/relocations', roles: ['ADMIN'] as RouteRole[] },
  adminSupport: { path: '/admin/support', roles: ['ADMIN'] as RouteRole[] },
  adminSuppliers: { path: '/admin/suppliers', roles: ['ADMIN'] as RouteRole[] },
  adminSuppliersNew: { path: '/admin/suppliers/new', roles: ['ADMIN'] as RouteRole[] },
  adminSuppliersDetail: { path: '/admin/suppliers/:id', roles: ['ADMIN'] as RouteRole[] },
  adminResources: { path: '/admin/resources', roles: ['ADMIN'] as RouteRole[] },
  adminResourcesNew: { path: '/admin/resources/new', roles: ['ADMIN'] as RouteRole[] },
  adminResourcesEdit: { path: '/admin/resources/:id', roles: ['ADMIN'] as RouteRole[] },
  adminEvents: { path: '/admin/events', roles: ['ADMIN'] as RouteRole[] },
  adminEventsEdit: { path: '/admin/events/:id', roles: ['ADMIN'] as RouteRole[] },
  adminCategories: { path: '/admin/resources/categories', roles: ['ADMIN'] as RouteRole[] },
  adminTags: { path: '/admin/resources/tags', roles: ['ADMIN'] as RouteRole[] },
  adminSources: { path: '/admin/resources/sources', roles: ['ADMIN'] as RouteRole[] },
  adminStagingDashboard: { path: '/admin/staging', roles: ['ADMIN'] as RouteRole[] },
  adminStagingResources: { path: '/admin/staging/resources', roles: ['ADMIN'] as RouteRole[] },
  adminStagingResourceDetail: { path: '/admin/staging/resources/:id', roles: ['ADMIN'] as RouteRole[] },
  adminStagingEvents: { path: '/admin/staging/events', roles: ['ADMIN'] as RouteRole[] },
  adminStagingEventDetail: { path: '/admin/staging/events/:id', roles: ['ADMIN'] as RouteRole[] },
  adminFreshness: { path: '/admin/freshness', roles: ['ADMIN'] as RouteRole[] },
  adminFreshnessCountries: { path: '/admin/freshness/countries', roles: ['ADMIN'] as RouteRole[] },
  adminFreshnessCities: { path: '/admin/freshness/cities', roles: ['ADMIN'] as RouteRole[] },
  adminFreshnessSources: { path: '/admin/freshness/sources', roles: ['ADMIN'] as RouteRole[] },
  adminFreshnessChanges: { path: '/admin/freshness/changes', roles: ['ADMIN'] as RouteRole[] },
  adminFreshnessStaleContent: { path: '/admin/freshness/stale-content', roles: ['ADMIN'] as RouteRole[] },
  adminCrawlSchedules: { path: '/admin/crawl/schedules', roles: ['ADMIN'] as RouteRole[] },
  adminCrawlJobRuns: { path: '/admin/crawl/job-runs', roles: ['ADMIN'] as RouteRole[] },
  adminCrawlJobRunDetail: { path: '/admin/crawl/job-runs/:id', roles: ['ADMIN'] as RouteRole[] },
  adminReviewQueue: { path: '/admin/review-queue', roles: ['ADMIN'] as RouteRole[] },
  adminReviewQueueDetail: { path: '/admin/review-queue/:id', roles: ['ADMIN'] as RouteRole[] },
  adminReviewQueueWorkload: { path: '/admin/review-queue/workload', roles: ['ADMIN'] as RouteRole[] },
  adminNotifications: { path: '/admin/notifications', roles: ['ADMIN'] as RouteRole[] },
  adminNotificationDetail: { path: '/admin/notifications/:id', roles: ['ADMIN'] as RouteRole[] },
  adminOpsSla: { path: '/admin/ops/sla', roles: ['ADMIN'] as RouteRole[] },
  adminOpsQueue: { path: '/admin/ops/queue', roles: ['ADMIN'] as RouteRole[] },
  adminOpsReviewers: { path: '/admin/ops/reviewers', roles: ['ADMIN'] as RouteRole[] },
  adminOpsDestinations: { path: '/admin/ops/destinations', roles: ['ADMIN'] as RouteRole[] },
  adminOpsNotifications: { path: '/admin/ops/notifications', roles: ['ADMIN'] as RouteRole[] },
};

export type RouteKey = keyof typeof ROUTE_DEFS;

export const buildRoute = (key: RouteKey, params?: Record<string, string>) =>
  generatePath(ROUTE_DEFS[key].path, params);

export const routeKeys = Object.keys(ROUTE_DEFS) as RouteKey[];
