-- P2-06d · Ingest corridor corpus → public.immigration_requirements
-- Generated by backend/scripts/ingest_corridor_corpus.py — do not hand-edit.

-- supersede stale rows for (IN, DE, blue_card) per supersedes_db_seed in in_de_corridor.json
DELETE FROM public.immigration_requirements WHERE corridor_from = 'IN' AND corridor_to = 'DE' AND visa_type = 'blue_card';

-- US→FR : 12 required_documents from us_fr_corridor.json
INSERT INTO public.immigration_requirements (corridor_from, corridor_to, visa_type, employee_type, document_type, document_name, is_required, is_conditional, condition_expression, freshness_days, requires_apostille, apostille_countries, requires_translation, translation_languages, can_be_prefilled, can_be_ocr_extracted, vault_field_mapping, typical_processing_days, book_early_flag, book_early_reason, success_tips, common_rejection_reasons, form_url, form_version, instructions_url, last_verified_date, source) VALUES
  ('US', 'FR', 'long_stay_visa', 'any', 'passport', 'Valid US Passport', true, false, NULL, NULL, false, '[]'::jsonb, false, '[]'::jsonb, true, true, 'identity.passport.number', 0, false, NULL, '[]'::jsonb, '[]'::jsonb, NULL, NULL, 'https://www.france-visas.gouv.fr/en/visa-de-long-sejour', '2026-06-04', 'corridor_corpus'),
  ('US', 'FR', 'long_stay_visa', 'any', 'biometric_photos', 'ICAO-compliant identity photographs (×3)', true, false, NULL, 180, false, '[]'::jsonb, false, '[]'::jsonb, false, false, NULL, 1, false, NULL, '[]'::jsonb, '[]'::jsonb, NULL, NULL, 'https://www.france-visas.gouv.fr/en/visa-de-long-sejour', '2026-06-04', 'corridor_corpus'),
  ('US', 'FR', 'long_stay_visa', 'salaried_employee', 'application_form', 'Long-stay visa application — Salarié (Cerfa 15615*01)', true, false, NULL, NULL, false, '[]'::jsonb, false, '[]'::jsonb, false, false, NULL, NULL, false, NULL, '[]'::jsonb, '[]'::jsonb, 'https://france-visas.gouv.fr/documents/d/france-visas/cerfa_15615-01_salarie', '15615*01', 'https://france-visas.gouv.fr/en/activite-salariee', '2026-06-04', 'corridor_corpus'),
  ('US', 'FR', 'long_stay_visa', 'salaried_employee', 'work_authorization', 'Work authorization issued by the DGEF (employer-initiated, prior to arrival)', true, true, 'visa_type == ''long_stay_visa'' AND employee_type IN (''salaried_employee'',''temporary_worker'')', NULL, false, '[]'::jsonb, false, '[]'::jsonb, false, false, NULL, 14, true, 'DGEF processes employer applications in 14 days typically; visa appointment cannot be booked before authorization issues.', '[]'::jsonb, '[]'::jsonb, NULL, NULL, 'https://www.service-public.fr/particuliers/vosdroits/F35602/1_0?lang=en', '2026-06-04', 'corridor_corpus'),
  ('US', 'FR', 'long_stay_visa', 'salaried_employee', 'employment_contract', 'Signed employment contract (CDI or CDD ≥3 months)', true, false, NULL, 180, false, '[]'::jsonb, false, '[]'::jsonb, false, false, NULL, NULL, false, NULL, '[]'::jsonb, '[]'::jsonb, NULL, NULL, 'https://www.service-public.fr/particuliers/vosdroits/F35602/1_0?lang=en', '2026-06-04', 'corridor_corpus'),
  ('US', 'FR', 'long_stay_visa', 'any', 'proof_of_accommodation', 'Proof of accommodation in France (lease, hotel reservation ≥3 months, or attestation d''hébergement)', true, false, NULL, 90, false, '[]'::jsonb, false, '[]'::jsonb, false, false, NULL, NULL, false, NULL, '[]'::jsonb, '[]'::jsonb, NULL, NULL, 'https://www.france-visas.gouv.fr/en/visa-de-long-sejour', '2026-06-04', 'corridor_corpus'),
  ('US', 'FR', 'long_stay_visa', 'any', 'financial_means', 'Proof of sufficient financial means (employment contract usually satisfies; otherwise bank statements covering 3 months)', true, false, NULL, 90, false, '[]'::jsonb, false, '[]'::jsonb, false, false, NULL, NULL, false, NULL, '[]'::jsonb, '[]'::jsonb, NULL, NULL, 'https://www.france-visas.gouv.fr/en/visa-de-long-sejour', '2026-06-04', 'corridor_corpus'),
  ('US', 'FR', 'long_stay_visa', 'any', 'health_insurance', 'Health insurance covering the full visa validity period', true, false, NULL, NULL, false, '[]'::jsonb, false, '[]'::jsonb, false, false, NULL, NULL, false, NULL, '[]'::jsonb, '[]'::jsonb, NULL, NULL, 'https://www.france-visas.gouv.fr/en/visa-de-long-sejour', '2026-06-04', 'corridor_corpus'),
  ('US', 'FR', 'passeport_talent', 'qualified_employee', 'employer_attestation', 'Employer attestation — Passeport Talent (Cerfa 15614*02)', true, false, NULL, NULL, false, '[]'::jsonb, false, '[]'::jsonb, false, false, NULL, NULL, false, NULL, '[]'::jsonb, '[]'::jsonb, 'https://france-visas.gouv.fr/documents/d/france-visas/cerfa_15614-02', '15614*02', 'https://france-visas.gouv.fr/en/talents-internationaux-et-attractivite-economique', '2026-06-04', 'corridor_corpus'),
  ('US', 'FR', 'passeport_talent', 'qualified_employee', 'degree_certificate', 'Master''s degree or equivalent (apostilled + sworn French translation)', true, false, NULL, NULL, true, '["US"]'::jsonb, true, '["fr"]'::jsonb, false, false, NULL, 21, true, 'Apostille + sworn French translation typically take 2–3 weeks combined.', '[]'::jsonb, '[]'::jsonb, NULL, NULL, 'https://www.service-public.fr/particuliers/vosdroits/F16922', '2026-06-04', 'corridor_corpus'),
  ('US', 'FR', 'passeport_talent', 'qualified_employee', 'employment_contract', 'Employment contract — CDI or CDD ≥3 months, gross annual salary ≥ €43,243', true, false, NULL, 180, false, '[]'::jsonb, true, '["fr"]'::jsonb, false, false, NULL, NULL, false, NULL, '[]'::jsonb, '[]'::jsonb, NULL, NULL, 'https://www.service-public.fr/particuliers/vosdroits/F16922', '2026-06-04', 'corridor_corpus'),
  ('US', 'FR', 'passeport_talent', 'qualified_employee', 'civil_status_document', 'Birth certificate (apostilled + sworn French translation); marriage certificate if accompanied by spouse', true, false, NULL, NULL, true, '["US"]'::jsonb, true, '["fr"]'::jsonb, false, false, NULL, 14, false, NULL, '[]'::jsonb, '[]'::jsonb, NULL, NULL, 'https://www.service-public.fr/particuliers/vosdroits/F35495/3_1_1_5_0_1?lang=en', '2026-06-04', 'corridor_corpus')
ON CONFLICT (corridor_from, corridor_to, visa_type, employee_type, document_type) DO UPDATE SET
    document_name = EXCLUDED.document_name,
    is_required = EXCLUDED.is_required,
    is_conditional = EXCLUDED.is_conditional,
    condition_expression = EXCLUDED.condition_expression,
    freshness_days = EXCLUDED.freshness_days,
    requires_apostille = EXCLUDED.requires_apostille,
    apostille_countries = EXCLUDED.apostille_countries,
    requires_translation = EXCLUDED.requires_translation,
    translation_languages = EXCLUDED.translation_languages,
    can_be_prefilled = EXCLUDED.can_be_prefilled,
    can_be_ocr_extracted = EXCLUDED.can_be_ocr_extracted,
    vault_field_mapping = EXCLUDED.vault_field_mapping,
    typical_processing_days = EXCLUDED.typical_processing_days,
    book_early_flag = EXCLUDED.book_early_flag,
    book_early_reason = EXCLUDED.book_early_reason,
    success_tips = EXCLUDED.success_tips,
    common_rejection_reasons = EXCLUDED.common_rejection_reasons,
    form_url = EXCLUDED.form_url,
    form_version = EXCLUDED.form_version,
    instructions_url = EXCLUDED.instructions_url,
    last_verified_date = EXCLUDED.last_verified_date,
    source = EXCLUDED.source,
    updated_at = now();

-- IN→DE : 11 required_documents from in_de_corridor.json
INSERT INTO public.immigration_requirements (corridor_from, corridor_to, visa_type, employee_type, document_type, document_name, is_required, is_conditional, condition_expression, freshness_days, requires_apostille, apostille_countries, requires_translation, translation_languages, can_be_prefilled, can_be_ocr_extracted, vault_field_mapping, typical_processing_days, book_early_flag, book_early_reason, success_tips, common_rejection_reasons, form_url, form_version, instructions_url, last_verified_date, source) VALUES
  ('IN', 'DE', 'blue_card', 'any', 'passport', 'Valid Indian Passport', true, false, NULL, NULL, false, '[]'::jsonb, false, '[]'::jsonb, true, true, 'identity.passport.number', 0, false, NULL, '[]'::jsonb, '[]'::jsonb, NULL, NULL, 'https://www.bamf.de/EN/Themen/MigrationAufenthalt/ZuwandererDrittstaaten/Migrathek/BlaueKarteEU/blauekarteeu-node.html', '2026-06-04', 'corridor_corpus'),
  ('IN', 'DE', 'blue_card', 'any', 'biometric_photos', 'Biometric passport photographs (×2)', true, false, NULL, 180, false, '[]'::jsonb, false, '[]'::jsonb, false, false, NULL, NULL, false, NULL, '[]'::jsonb, '[]'::jsonb, NULL, NULL, 'https://www.make-it-in-germany.com/en/visa-residence/types/eu-blue-card', '2026-06-04', 'corridor_corpus'),
  ('IN', 'DE', 'blue_card', 'any', 'application_form', 'National visa application form (Type D, signed)', true, false, NULL, NULL, false, '[]'::jsonb, false, '[]'::jsonb, false, false, NULL, NULL, false, NULL, '[]'::jsonb, '[]'::jsonb, 'https://www.auswaertiges-amt.de/en/visa-service', NULL, 'https://www.auswaertiges-amt.de/en/visa-service/buergerservice/faq/02a-what-is-the-blue-card/606754', '2026-06-04', 'corridor_corpus'),
  ('IN', 'DE', 'blue_card', 'any', 'degree_certificate', 'Indian university degree certificate + transcripts (with MEA apostille and sworn German/English translation)', true, false, NULL, NULL, true, '["IN"]'::jsonb, true, '["de", "en"]'::jsonb, false, false, NULL, 21, true, 'MEA apostille typically takes 5-7 business days; sworn German translation adds 1-2 weeks. Start at least 30 days before visa appointment.', '[]'::jsonb, '[]'::jsonb, 'https://anabin.kmk.org/anabin/hochschulen.html', NULL, 'https://www.make-it-in-germany.com/en/working-in-germany/recognition/foreign-academic-qualifications', '2026-06-04', 'corridor_corpus'),
  ('IN', 'DE', 'blue_card', 'any', 'qualification_recognition', 'Anabin database verification (university H+ status and degree H+/equivalent)', true, false, NULL, NULL, false, '[]'::jsonb, false, '[]'::jsonb, false, false, NULL, 0, false, NULL, '[]'::jsonb, '[]'::jsonb, NULL, NULL, 'https://anabin.kmk.org/anabin/hochschulen.html', '2026-06-04', 'corridor_corpus'),
  ('IN', 'DE', 'blue_card', 'any', 'employment_contract', 'Signed employment contract or binding job offer — gross annual salary ≥ €50,700 (general) or ≥ €45,934.20 (shortage occupation or recent graduate)', true, false, NULL, 180, false, '[]'::jsonb, true, '["de", "en"]'::jsonb, false, false, NULL, 5, false, NULL, '[]'::jsonb, '[]'::jsonb, NULL, NULL, 'https://www.bamf.de/EN/Themen/MigrationAufenthalt/ZuwandererDrittstaaten/Migrathek/BlaueKarteEU/blauekarteeu-node.html', '2026-06-04', 'corridor_corpus'),
  ('IN', 'DE', 'blue_card', 'any', 'proof_of_accommodation', 'Proof of accommodation in Germany (rental contract, registration confirmation, or temporary booking)', true, true, 'required_at_city_registration_within_14_days_of_arrival', 90, false, '[]'::jsonb, false, '[]'::jsonb, false, false, NULL, NULL, false, NULL, '[]'::jsonb, '[]'::jsonb, NULL, NULL, 'https://www.make-it-in-germany.com/en/visa-residence/types/eu-blue-card', '2026-06-04', 'corridor_corpus'),
  ('IN', 'DE', 'blue_card', 'any', 'health_insurance', 'Travel health insurance for the visa-entry period (statutory German health insurance through employer takes over after registration)', true, false, NULL, NULL, false, '[]'::jsonb, false, '[]'::jsonb, false, false, NULL, NULL, false, NULL, '[]'::jsonb, '[]'::jsonb, NULL, NULL, 'https://www.make-it-in-germany.com/en/visa-residence/types/eu-blue-card', '2026-06-04', 'corridor_corpus'),
  ('IN', 'DE', 'blue_card', 'any', 'cv', 'Curriculum Vitae (Europass format preferred) + cover letter', true, false, NULL, 90, false, '[]'::jsonb, false, '[]'::jsonb, false, false, NULL, NULL, false, NULL, '[]'::jsonb, '[]'::jsonb, NULL, NULL, 'https://www.make-it-in-germany.com/en/visa-residence/types/eu-blue-card', '2026-06-04', 'corridor_corpus'),
  ('IN', 'DE', 'blue_card', 'any', 'civil_status_document', 'Birth certificate (with MEA apostille and sworn German translation); marriage certificate if accompanied by spouse', true, false, NULL, NULL, true, '["IN"]'::jsonb, true, '["de"]'::jsonb, false, false, NULL, 21, false, NULL, '[]'::jsonb, '[]'::jsonb, NULL, NULL, 'https://www.make-it-in-germany.com/en/visa-residence/types/eu-blue-card', '2026-06-04', 'corridor_corpus'),
  ('IN', 'DE', 'blue_card', 'any', 'visa_fee', 'Visa application fee — €75 (2026)', true, false, NULL, NULL, false, '[]'::jsonb, false, '[]'::jsonb, false, false, NULL, NULL, false, NULL, '[]'::jsonb, '[]'::jsonb, NULL, NULL, 'https://www.auswaertiges-amt.de/en/visa-service/buergerservice/faq/02a-what-is-the-blue-card/606754', '2026-06-04', 'corridor_corpus')
ON CONFLICT (corridor_from, corridor_to, visa_type, employee_type, document_type) DO UPDATE SET
    document_name = EXCLUDED.document_name,
    is_required = EXCLUDED.is_required,
    is_conditional = EXCLUDED.is_conditional,
    condition_expression = EXCLUDED.condition_expression,
    freshness_days = EXCLUDED.freshness_days,
    requires_apostille = EXCLUDED.requires_apostille,
    apostille_countries = EXCLUDED.apostille_countries,
    requires_translation = EXCLUDED.requires_translation,
    translation_languages = EXCLUDED.translation_languages,
    can_be_prefilled = EXCLUDED.can_be_prefilled,
    can_be_ocr_extracted = EXCLUDED.can_be_ocr_extracted,
    vault_field_mapping = EXCLUDED.vault_field_mapping,
    typical_processing_days = EXCLUDED.typical_processing_days,
    book_early_flag = EXCLUDED.book_early_flag,
    book_early_reason = EXCLUDED.book_early_reason,
    success_tips = EXCLUDED.success_tips,
    common_rejection_reasons = EXCLUDED.common_rejection_reasons,
    form_url = EXCLUDED.form_url,
    form_version = EXCLUDED.form_version,
    instructions_url = EXCLUDED.instructions_url,
    last_verified_date = EXCLUDED.last_verified_date,
    source = EXCLUDED.source,
    updated_at = now();
