-- ─────────────────────────────────────────────────────────────────────────────
-- exception_requests hardening migration
--
-- Fixes three gaps left by 20260503100000_p2_exception_requests.sql:
--
--   1. Schema gap: recommended_action column was present in the SQLite
--      auto-create (database.py) but missing from the Postgres table.
--
--   2. CHECK constraint gap: points_threshold_unconfirmed was added in P5
--      (UK Skilled Worker sprint) but not in the original CHECK list.
--
--   3. RLS gap: the P2 migration left a placeholder policy that grants full
--      access to all roles. Replaced here with:
--        • service_role  — full read/write (used by the FastAPI backend)
--        • HR users      — select + insert + update on their own cases
--                          (gated through case_assignments.hr_user_id)
--        • Employee users— select-only on their own cases
--                          (gated through case_assignments.employee_user_id)
--
--   4. Performance: compound indexes for the common query shapes.
--
-- Touch policy: ALTER TABLE only. No new tables. Safe to run on a live DB.
-- ─────────────────────────────────────────────────────────────────────────────

BEGIN;

-- ── 1. Add recommended_action column if missing ───────────────────────────────

ALTER TABLE public.exception_requests
  ADD COLUMN IF NOT EXISTS recommended_action TEXT NULL;

COMMENT ON COLUMN public.exception_requests.recommended_action IS
  'Suggested next action for HR, generated by ExceptionRequestService.';

-- ── 2. Extend exception_type CHECK to include points_threshold_unconfirmed ────
-- Postgres does not support ALTER CONSTRAINT, so we drop and re-add.
-- The constraint name is the auto-generated default from the CREATE TABLE.

ALTER TABLE public.exception_requests
  DROP CONSTRAINT IF EXISTS exception_requests_exception_type_check;

ALTER TABLE public.exception_requests
  ADD CONSTRAINT exception_requests_exception_type_check
  CHECK (exception_type IN (
    'tenure_insufficient',          -- employee < 1 yr at company (L1B / Japan ICT)
    'no_sponsoring_entity',         -- no legal entity to petition / sponsor (L1B / UK CoS)
    'timeline_breach',              -- move date < minimum processing window
    'cost_threshold',               -- estimated cost > policy cap
    'role_category_ambiguous',      -- visa sub-category unclear (Japan COE / L1B)
    'dual_intent_conflict',         -- visa type prohibits dual intent
    'points_threshold_unconfirmed', -- UK Skilled Worker ≥70 points not verified (P5)
    'policy_custom'                 -- catch-all for HR-defined exceptions
  ));

-- ── 3. Replace placeholder RLS with granular policies ────────────────────────

-- 3a. Remove the catch-all placeholder (grants everything to everyone).
DROP POLICY IF EXISTS exception_requests_service_role ON public.exception_requests;

-- 3b. service_role — full access for the FastAPI backend.
-- The backend connects with the service role key and must be able to insert,
-- update, and read rows without going through user-scoped RLS.
CREATE POLICY exception_requests_service_role
  ON public.exception_requests
  FOR ALL
  TO service_role
  USING (TRUE)
  WITH CHECK (TRUE);

-- 3c. HR read — HR users can SELECT exception flags for their assigned cases.
-- "HR user for a case" = the user whose uid matches hr_user_id in case_assignments
-- for the same case_id. This mirrors the pattern used in case_milestones.
DROP POLICY IF EXISTS exception_requests_hr_select ON public.exception_requests;
CREATE POLICY exception_requests_hr_select
  ON public.exception_requests
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.case_assignments ca
      WHERE ca.case_id = exception_requests.case_id
        AND ca.hr_user_id = auth.uid()::text
    )
  );

-- 3d. HR write — HR users can INSERT and UPDATE flags for their assigned cases.
-- Employees are explicitly excluded (they cannot create or modify exception rows).
DROP POLICY IF EXISTS exception_requests_hr_insert ON public.exception_requests;
CREATE POLICY exception_requests_hr_insert
  ON public.exception_requests
  FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.case_assignments ca
      WHERE ca.case_id = exception_requests.case_id
        AND ca.hr_user_id = auth.uid()::text
    )
  );

DROP POLICY IF EXISTS exception_requests_hr_update ON public.exception_requests;
CREATE POLICY exception_requests_hr_update
  ON public.exception_requests
  FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.case_assignments ca
      WHERE ca.case_id = exception_requests.case_id
        AND ca.hr_user_id = auth.uid()::text
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.case_assignments ca
      WHERE ca.case_id = exception_requests.case_id
        AND ca.hr_user_id = auth.uid()::text
    )
  );

-- 3e. Employee read — employees can SELECT flags for their own cases.
-- Read-only: employees cannot create or modify exception flags.
-- This allows the employee-facing app to show a "case under review" indicator
-- without exposing the full HR-internal reason/recommended_action detail
-- (that filtering is handled at the API layer in list_case_exceptions).
DROP POLICY IF EXISTS exception_requests_employee_select ON public.exception_requests;
CREATE POLICY exception_requests_employee_select
  ON public.exception_requests
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.case_assignments ca
      WHERE ca.case_id = exception_requests.case_id
        AND ca.employee_user_id = auth.uid()::text
    )
  );

-- ── 4. Compound performance indexes ──────────────────────────────────────────
-- The primary query shape is:
--   SELECT ... FROM exception_requests WHERE case_id = $1
--   ORDER BY CASE severity WHEN 'blocker' THEN 0 ELSE 1 END, created_at DESC
-- and the status-filter variant:
--   WHERE case_id = $1 AND status = 'pending'

CREATE INDEX IF NOT EXISTS idx_exception_requests_case_status
  ON public.exception_requests (case_id, status);

CREATE INDEX IF NOT EXISTS idx_exception_requests_case_severity
  ON public.exception_requests (case_id, severity, status);

-- Partial index: pending blockers are the hot path for the dashboard.
CREATE INDEX IF NOT EXISTS idx_exception_requests_pending_blockers
  ON public.exception_requests (case_id, created_at DESC)
  WHERE status = 'pending' AND severity = 'blocker';

-- ── 5. Column comments for discoverability ────────────────────────────────────

COMMENT ON TABLE public.exception_requests IS
  'Immigration and policy exception flags raised by ExceptionRequestService '
  'during relocation case timeline generation. HR must approve or deny each '
  'blocker before a case can proceed.';

COMMENT ON COLUMN public.exception_requests.exception_type IS
  'Machine-readable exception category. Validated against CHECK constraint.';

COMMENT ON COLUMN public.exception_requests.severity IS
  'blocker: case cannot proceed without HR sign-off. '
  'warning: HR awareness item; case may proceed.';

COMMENT ON COLUMN public.exception_requests.status IS
  'pending: awaiting HR action. '
  'approved: HR signed off. '
  'denied: HR refused; case remains blocked. '
  'escalated: referred to leadership/legal/finance. '
  'withdrawn: flag no longer relevant.';

COMMENT ON COLUMN public.exception_requests.resolved_by IS
  'auth.uid() of the HR user who resolved the flag (set by the PATCH endpoint).';

COMMIT;
