#!/usr/bin/env python3
"""Generate the IE-P0 re-source gap-fill candidate load migration from the batch NDJSON.

Source of truth: src/ie-p0-resource-gapfill.ndjson (sha256 recorded in manifest.json).
Regenerate, do not hand-edit the .sql:  python3 gen_load.py

Governance (see README.md): candidates only. review_status='pending',
verification_status='representative', ON CONFLICT (id) DO NOTHING so a re-run never
overwrites a reviewer's later decision. Nothing here approves or serves a fact.
"""
from __future__ import annotations
import json
import hashlib
from pathlib import Path

BATCH = "ie-p0-resource-gapfill-2026-09-09"
MIGRATION_VERSION = "20261133000000"
HERE = Path(__file__).resolve().parent
REPO = HERE.parents[2]  # docs/imports/<batch>/ -> repo root
NDJSON = HERE / "src" / "ie-p0-resource-gapfill.ndjson"
OUT = REPO / "supabase" / "migrations" / f"{MIGRATION_VERSION}_ie_p0_resource_gapfill_candidates.sql"

COLUMNS = [
    "id", "country_code", "purpose", "pillar", "title", "description",
    "severity", "owner", "required_fields_json", "citations_json",
    "applies_to_nationality_classes_json", "non_obvious", "timing",
    "verification_status", "review_status", "last_verified_at",
]


def sql_str(v: str) -> str:
    return "'" + v.replace("'", "''") + "'"


def sql_val(col: str, o: dict) -> str:
    if col == "last_verified_at":
        return "NOW()"
    if col == "non_obvious":
        return "TRUE" if o["non_obvious"] else "FALSE"
    if col in ("required_fields_json", "citations_json"):
        return sql_str(json.dumps(o[col], ensure_ascii=False, separators=(", ", ": ")))
    if col == "applies_to_nationality_classes_json":
        v = o.get("applies_to_nationality_classes_json")
        return "NULL" if v is None else sql_str(json.dumps(v, ensure_ascii=False))
    return sql_str(str(o[col]))


def main() -> None:
    records = [json.loads(l) for l in NDJSON.read_text(encoding="utf-8").splitlines() if l.strip()]
    sha = hashlib.sha256(NDJSON.read_bytes()).hexdigest()
    rows = []
    for o in records:
        vals = ",\n     ".join(sql_val(c, o) for c in COLUMNS)
        rows.append(f"    (\n     {vals}\n    )")
    body = ",\n".join(rows)
    header = f"""-- ============================================================================
-- IE-P0 (destination Ireland) re-source gap-fill -- {len(records)} candidate records.
--
-- Source of truth: docs/imports/{BATCH}/src/ie-p0-resource-gapfill.ndjson
--   sha256 {sha}
-- GENERATED by docs/imports/{BATCH}/gen_load.py -- regenerate, do not hand-edit.
--
-- These fill three gaps left open by the 2026-08-31 IE-P0 sweep, each sourced to a
-- verbatim quote from an official Irish source (revenue.ie, citizensinformation.ie).
-- They are NET-NEW ids (no collision with the 145 existing ie_ facts in prod).
--
-- CANDIDATES ONLY. review_status='pending' is EXPLICIT (the column defaults to
-- 'approved' and requirements_builder serves only approved rows, so a plain INSERT
-- would publish unreviewed facts). verification_status='representative' -- NOTHING is
-- verified. A fact reaches a customer only after a human approves it.
--
-- Idempotent: ON CONFLICT (id) DO NOTHING. Re-running never changes an existing row,
-- so a reviewer's later approval/rejection is never overwritten.
-- ============================================================================

INSERT INTO public.requirement_items
    ({", ".join(COLUMNS)})
VALUES
{body}
ON CONFLICT (id) DO NOTHING;
"""
    OUT.write_text(header, encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)} ({len(records)} records, sha256 {sha[:12]}...)")


if __name__ == "__main__":
    main()
