"""TAX_CERT extraction agent tests (C2-02b).

Two layers:

1. Agent-definition checks — CI-green, no LLM/DB/PDF. Confirm each of the
   three tax_cert agents loads its prompt and builds an ExtractionAgent whose
   ``output_schema_required_keys`` match the prompt's documented contract.

2. Ground-truth fixture parametrization — one case per fixture. The source
   PDFs are owned by C1-17 (pilot corpus) and are NOT in this branch, so each
   parametrized case ``xfail``s until the matching ``.pdf`` lands. Once it
   does, ``run_agent_for_fixture`` can be filled in to assert field accuracy.

Run with:
    PYTHONPATH=. python3 -m pytest backend/tests/test_extraction_tax_cert.py -v
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from backend.relopass.agents.extraction import (
    load_tax_cert_de_prompt,
    load_tax_cert_fr_prompt,
    load_tax_cert_no_prompt,
)
from backend.relopass.agents.extraction.tax_cert_de import _build_agent as _build_de
from backend.relopass.agents.extraction.tax_cert_fr import _build_agent as _build_fr
from backend.relopass.agents.extraction.tax_cert_no import _build_agent as _build_no

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "tax_certs"


# ─────────────────────────────────────────────────────────────────────────────
# Agent-definition checks
# ─────────────────────────────────────────────────────────────────────────────


class TestAgentDefinitions:
    def test_fr_prompt_loads(self) -> None:
        assert "avis d'imposition" in load_tax_cert_fr_prompt().lower()

    def test_de_prompt_loads(self) -> None:
        assert "lohnsteuerbescheinigung" in load_tax_cert_de_prompt().lower()

    def test_no_prompt_loads(self) -> None:
        assert "skattemelding" in load_tax_cert_no_prompt().lower()

    def test_fr_required_keys(self) -> None:
        keys = _build_fr().output_schema_required_keys
        for k in ("is_avis_imposition", "tax_id", "residence_country_iso3", "findings"):
            assert k in keys

    def test_de_required_keys(self) -> None:
        keys = _build_de().output_schema_required_keys
        for k in ("is_tax_document", "document_subtype", "is_employer_issued", "tax_id"):
            assert k in keys

    def test_no_required_keys(self) -> None:
        keys = _build_no().output_schema_required_keys
        for k in ("is_tax_document", "document_subtype", "holder_national_id_redacted", "tax_id"):
            assert k in keys

    def test_agent_names_distinct(self) -> None:
        names = {_build_fr().name, _build_de().name, _build_no().name}
        assert names == {"tax_cert_fr", "tax_cert_de", "tax_cert_no"}


# ─────────────────────────────────────────────────────────────────────────────
# Ground-truth fixtures (xfail until C1-17 PDFs land)
# ─────────────────────────────────────────────────────────────────────────────

FIXTURE_STEMS = [
    "fr_01_dgfip_single",
    "fr_02_dgfip_joint",
    "fr_03_dgfip_residency_mismatch",
    "de_01_lohnsteuer_clean",
    "de_02_bescheid_finanzamt",
    "de_03_partial_year",
    "no_01_skattemelding",
    "no_02_skatteoppgjor",
    "no_03_residency_mismatch",
]


@pytest.mark.parametrize("stem", FIXTURE_STEMS)
def test_extraction_matches_ground_truth(stem: str) -> None:
    expected_path = FIXTURE_DIR / f"{stem}.expected.json"
    assert expected_path.exists(), f"missing ground-truth file: {expected_path}"
    expected = json.loads(expected_path.read_text(encoding="utf-8"))

    # The ground-truth file must declare its country + carry the canonical keys.
    meta = expected.get("_fixture_metadata", {})
    assert meta.get("country") in {"FRA", "DEU", "NOR"}
    assert "tax_id" in expected
    assert "residence_country_iso3" in expected
    assert "findings" in expected

    pdf = FIXTURE_DIR / f"{stem}.pdf"
    if not pdf.exists():
        pytest.xfail(f"{stem}.pdf not yet generated by C1-17 — extraction not runnable")

    # When the PDF lands, run the matching agent and assert field accuracy
    # (≥0.90 per country, per the fixtures README scoring rubric).
    raise AssertionError("PDF present but run_agent_for_fixture is not implemented yet")
