/**
 * analytics.ts — TypeScript types for the ReloPass analytics schema
 * ─────────────────────────────────────────────────────────────────────────────
 * Mirrors the Supabase tables created in:
 *   migration: 20260523000000_analytics_events_and_daily_summaries.sql
 *
 * These types are hand-authored to match the migration exactly.
 * Run `supabase gen types typescript` to regenerate from live DB if the
 * schema changes.
 * ─────────────────────────────────────────────────────────────────────────────
 */

// ─── Enums ────────────────────────────────────────────────────────────────────

/** The channel through which an event arrived. Matches CHECK constraint. */
export type EventSource = 'web' | 'api' | 'agent' | 'scheduler';

/** Top-level event categories. Extend as new surfaces are instrumented. */
export type EventType =
  // Navigation
  | 'page_view'
  | 'page_exit'
  // Auth
  | 'user_signed_in'
  | 'user_signed_out'
  | 'user_signed_up'
  // HR buyer actions
  | 'assignment_created'
  | 'paywall_impression'
  | 'payment_initiated'
  | 'payment_completed'
  | 'assignment_submitted'
  | 'assignment_cancelled'
  | 'assignment_completed'
  | 'assignment_disputed'
  // Employee actions
  | 'employee_portal_opened'
  | 'employee_document_uploaded'
  | 'employee_task_completed'
  // Supplier actions
  | 'supplier_assignment_accepted'
  | 'supplier_assignment_declined'
  | 'supplier_milestone_submitted'
  // Policy assistant
  | 'policy_question_asked'
  | 'policy_answer_rated'
  | 'policy_document_viewed'
  // Platform health
  | 'api_error'
  | 'api_slow_query'
  | 'edge_function_error'
  | 'e2e_test_run'
  // Support
  | 'support_ticket_created'
  | 'support_ticket_resolved'
  | (string & {}); // allow arbitrary strings for future extensibility

/** Category lens for daily_summaries. Matches CHECK constraint. */
export type SummaryType = 'user_behaviour' | 'assignments' | 'platform_health';

// ─── Row types ────────────────────────────────────────────────────────────────

/**
 * A single row in the `public.events` table.
 * The table is append-only — no UPDATE or DELETE is permitted via RLS.
 */
export interface EventRow {
  id: string;            // uuid
  created_at: string;    // ISO 8601 timestamptz

  /** High-level action that occurred. */
  event_type: EventType;

  /** The domain object the event is about (e.g. 'assignment', 'case'). */
  entity_type: string | null;

  /** UUID or slug of the affected entity. */
  entity_id: string | null;

  /**
   * SHA-256 hash of auth.uid() — never stores raw PII.
   * Null for anonymous/unauthenticated events.
   */
  user_id: string | null;

  /** UUID of the HR company associated with this event. */
  company_id: string | null;

  /** Client-generated session token for grouping events in a single session. */
  session_id: string | null;

  /** How the event arrived. */
  source: EventSource;

  /** Arbitrary event-specific payload (e.g. { page: '/assignments', duration_ms: 342 }). */
  properties: Record<string, unknown>;
}

/**
 * Payload shape for inserting a new event.
 * `id` and `created_at` are generated by the database.
 */
export type EventInsert = Omit<EventRow, 'id' | 'created_at'> & {
  id?: string;
  created_at?: string;
};

/**
 * A single row in the `public.daily_summaries` table.
 * Written by the nightly aggregation Edge Function (service-role).
 */
export interface DailySummaryRow {
  id: string;            // uuid
  created_at: string;    // ISO 8601 timestamptz

  /** Calendar date this summary covers (YYYY-MM-DD). */
  date: string;

  /** Which lens this summary is written from. */
  summary_type: SummaryType;

  /** AI-generated natural-language digest of the day's events. */
  summary_text: string;

  /**
   * Structured counts produced by the aggregation job.
   * Shape varies by summary_type, e.g.:
   *   user_behaviour:  { page_views: 120, unique_users: 34, ... }
   *   assignments:     { created: 5, completed: 3, declined: 1, ... }
   *   platform_health: { errors: 7, slow_queries: 2, ... }
   */
  raw_counts: Record<string, unknown>;

  /**
   * Anomaly flags raised by the nightly job.
   * Each entry: { type: string; message: string; severity: 'low'|'medium'|'high' }
   */
  anomalies: Array<{
    type: string;
    message: string;
    severity: 'low' | 'medium' | 'high';
  }>;
}

/**
 * Payload for upserting a daily summary.
 * The nightly Edge Function upserts on (date, summary_type).
 */
export type DailySummaryInsert = Omit<DailySummaryRow, 'id' | 'created_at'> & {
  id?: string;
  created_at?: string;
};
