"""
IMM-03 · Immigration Requirements Seed Data

Run this script once to populate the immigration_requirements table.
Safe to re-run — uses INSERT ... ON CONFLICT DO NOTHING.

Usage:
    cd backend
    python -m app.seed_immigration_requirements

Corridors covered:
  FR → DE  (blue_card, skilled_worker, posted_worker)
  UK → FR  (long_stay_visa)
  UK → DE  (skilled_worker, blue_card)
  US → DE  (blue_card, skilled_worker)
  IN → DE  (skilled_worker, blue_card)
  FR → UK  (skilled_worker)
  DE → UK  (skilled_worker)
  FR → US  (l1_visa, o1_visa)
"""
from __future__ import annotations

import json
import logging
import sys

from sqlalchemy import text

# Allow running as: python -m app.seed_immigration_requirements
# from the backend/ directory
if __name__ == "__main__":
    import os
    sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

from app.db import SessionLocal

log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Seed rows
# Each dict maps exactly to the immigration_requirements table columns.
# Omitted optional columns default to NULL / False.
# ---------------------------------------------------------------------------

REQUIREMENTS: list[dict] = [

    # =========================================================================
    # FR → DE  |  blue_card
    # =========================================================================
    {
        "corridor_from": "FR", "corridor_to": "DE", "visa_type": "blue_card",
        "employee_type": "any",
        "document_type": "passport",
        "document_name": "Valid Passport",
        "is_required": True, "is_conditional": False,
        "freshness_days": None,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": False, "can_be_ocr_extracted": True,
        "typical_processing_days": 0, "book_early_flag": False,
        "success_tips": [
            "Passport must be valid for at least 6 months beyond visa end date.",
            "Ensure all personal details match exactly across all documents."
        ],
        "common_rejection_reasons": [
            "Passport expiry within 6 months of visa end date.",
            "Name mismatch between passport and employment contract."
        ],
        "form_url": None, "form_version": None,
    },
    {
        "corridor_from": "FR", "corridor_to": "DE", "visa_type": "blue_card",
        "employee_type": "any",
        "document_type": "employment_contract",
        "document_name": "Employment Contract",
        "is_required": True, "is_conditional": False,
        "freshness_days": 90,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": True, "translation_languages": ["de"],
        "can_be_prefilled": True, "can_be_ocr_extracted": False,
        "typical_processing_days": 5, "book_early_flag": False,
        "success_tips": [
            "Contract must state gross annual salary ≥ €45,300 (general) or €41,042 (shortage occupation).",
            "Contract must be signed by both employer and employee.",
            "Job title must clearly correspond to the recognised occupation.",
        ],
        "common_rejection_reasons": [
            "Salary below the Blue Card minimum threshold.",
            "Contract missing mandatory EU Blue Card salary clause.",
            "Unsigned contract.",
        ],
        "form_url": None, "form_version": None,
    },
    {
        "corridor_from": "FR", "corridor_to": "DE", "visa_type": "blue_card",
        "employee_type": "any",
        "document_type": "degree_certificate",
        "document_name": "University Degree Certificate",
        "is_required": True, "is_conditional": False,
        "freshness_days": None,
        "requires_apostille": True, "apostille_countries": ["FR"],
        "requires_translation": True, "translation_languages": ["de"],
        "can_be_prefilled": False, "can_be_ocr_extracted": True,
        "typical_processing_days": 21, "book_early_flag": True,
        "book_early_reason": "Apostille + certified translation takes 3–4 weeks.",
        "success_tips": [
            "Degree must be listed in the anabin database as H+ or equivalent.",
            "If degree is not in anabin, apply for a Statement of Comparability (ZAB) — takes 4–8 weeks.",
            "Include academic transcripts alongside the degree certificate.",
        ],
        "common_rejection_reasons": [
            "Degree not recognised by German authorities (not in anabin).",
            "Translation not from a sworn/certified translator.",
            "Missing academic transcripts.",
        ],
        "form_url": "https://anabin.kmk.org/anabin/anabinsuche/hochschulsuche.html",
        "form_version": None,
    },
    {
        "corridor_from": "FR", "corridor_to": "DE", "visa_type": "blue_card",
        "employee_type": "any",
        "document_type": "biometric_photo",
        "document_name": "Biometric Passport Photos (2x)",
        "is_required": True, "is_conditional": False,
        "freshness_days": 90,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": False, "can_be_ocr_extracted": False,
        "typical_processing_days": 1, "book_early_flag": False,
        "success_tips": [
            "35mm × 45mm, white background, taken within 3 months.",
            "Neutral facial expression, mouth closed.",
        ],
        "common_rejection_reasons": [
            "Non-white background.", "Photo older than 6 months.",
        ],
        "form_url": None, "form_version": None,
    },
    {
        "corridor_from": "FR", "corridor_to": "DE", "visa_type": "blue_card",
        "employee_type": "any",
        "document_type": "visa_application_form",
        "document_name": "National Visa Application Form (Type D)",
        "is_required": True, "is_conditional": False,
        "freshness_days": 90,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": True, "can_be_ocr_extracted": False,
        "typical_processing_days": 0, "book_early_flag": False,
        "success_tips": [
            "Complete in block capitals. Use black ink if handwritten.",
            "Ensure travel history section covers last 10 years.",
        ],
        "common_rejection_reasons": [
            "Inconsistent travel dates.",
            "Missing signature on page 2.",
        ],
        "form_url": "https://videx-national.diplo.de/videx/visum-erfassung/",
        "form_version": "2024-01",
    },
    {
        "corridor_from": "FR", "corridor_to": "DE", "visa_type": "blue_card",
        "employee_type": "any",
        "document_type": "proof_of_accommodation",
        "document_name": "Proof of Accommodation in Germany",
        "is_required": True, "is_conditional": False,
        "freshness_days": 90,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": True, "translation_languages": ["de"],
        "can_be_prefilled": False, "can_be_ocr_extracted": False,
        "typical_processing_days": 3, "book_early_flag": False,
        "success_tips": [
            "Rental contract or employer-provided housing confirmation letter.",
            "Address must match the Anmeldung (registration) address.",
        ],
        "common_rejection_reasons": [
            "Document not dated within 3 months.",
        ],
        "form_url": None, "form_version": None,
    },
    {
        "corridor_from": "FR", "corridor_to": "DE", "visa_type": "blue_card",
        "employee_type": "any",
        "document_type": "spouse_marriage_certificate",
        "document_name": "Marriage Certificate (if spouse joining)",
        "is_required": False, "is_conditional": True,
        "condition_expression": "marital_status = married",
        "freshness_days": None,
        "requires_apostille": True, "apostille_countries": ["FR"],
        "requires_translation": True, "translation_languages": ["de"],
        "can_be_prefilled": False, "can_be_ocr_extracted": True,
        "typical_processing_days": 14, "book_early_flag": True,
        "book_early_reason": "Apostille from French authorities takes 1–3 weeks.",
        "success_tips": [
            "Official extract from the mairie — not a church certificate.",
        ],
        "common_rejection_reasons": [
            "Church-issued certificate not accepted — must be civil registry.",
        ],
        "form_url": None, "form_version": None,
    },
    {
        "corridor_from": "FR", "corridor_to": "DE", "visa_type": "blue_card",
        "employee_type": "any",
        "document_type": "child_birth_certificate",
        "document_name": "Birth Certificate(s) for Dependent Children",
        "is_required": False, "is_conditional": True,
        "condition_expression": "has_dependents = true",
        "freshness_days": None,
        "requires_apostille": True, "apostille_countries": ["FR"],
        "requires_translation": True, "translation_languages": ["de"],
        "can_be_prefilled": False, "can_be_ocr_extracted": True,
        "typical_processing_days": 14, "book_early_flag": True,
        "book_early_reason": "Apostille takes 1–3 weeks per document.",
        "success_tips": [
            "Request from the mairie where birth was registered.",
            "One certificate per child required.",
        ],
        "common_rejection_reasons": [
            "Missing child's name or parent names on certificate.",
        ],
        "form_url": None, "form_version": None,
    },

    # =========================================================================
    # FR → DE  |  skilled_worker  (§18a AufenthG)
    # =========================================================================
    {
        "corridor_from": "FR", "corridor_to": "DE", "visa_type": "skilled_worker",
        "employee_type": "any",
        "document_type": "passport",
        "document_name": "Valid Passport",
        "is_required": True, "is_conditional": False,
        "freshness_days": None,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": False, "can_be_ocr_extracted": True,
        "typical_processing_days": 0, "book_early_flag": False,
        "success_tips": ["6 months validity beyond visa end date required."],
        "common_rejection_reasons": ["Passport expiry too close to visa end date."],
        "form_url": None, "form_version": None,
    },
    {
        "corridor_from": "FR", "corridor_to": "DE", "visa_type": "skilled_worker",
        "employee_type": "any",
        "document_type": "employment_contract",
        "document_name": "Employment Contract",
        "is_required": True, "is_conditional": False,
        "freshness_days": 90,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": True, "translation_languages": ["de"],
        "can_be_prefilled": True, "can_be_ocr_extracted": False,
        "typical_processing_days": 5, "book_early_flag": False,
        "success_tips": [
            "Salary must meet the collective agreement rate for the occupation.",
            "Job description must match the recognised qualification.",
        ],
        "common_rejection_reasons": [
            "Salary below collective agreement minimum.",
            "Mismatch between job description and qualification.",
        ],
        "form_url": None, "form_version": None,
    },
    {
        "corridor_from": "FR", "corridor_to": "DE", "visa_type": "skilled_worker",
        "employee_type": "any",
        "document_type": "qualification_recognition",
        "document_name": "Proof of Qualification Recognition (anabin / Statement of Comparability)",
        "is_required": True, "is_conditional": False,
        "freshness_days": None,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": True, "translation_languages": ["de"],
        "can_be_prefilled": False, "can_be_ocr_extracted": False,
        "typical_processing_days": 56, "book_early_flag": True,
        "book_early_reason": "ZAB Statement of Comparability takes 4–8 weeks.",
        "success_tips": [
            "Apply via the Central Office for Foreign Education (KMK/ZAB) if not in anabin.",
            "Vocational qualifications: apply to the relevant German chamber (IHK/HWK).",
        ],
        "common_rejection_reasons": [
            "Qualification not recognised — must obtain ZAB statement first.",
        ],
        "form_url": "https://www.kmk.org/zab/central-office-for-foreign-education.html",
        "form_version": None,
    },
    {
        "corridor_from": "FR", "corridor_to": "DE", "visa_type": "skilled_worker",
        "employee_type": "any",
        "document_type": "degree_certificate",
        "document_name": "University Degree / Vocational Qualification Certificate",
        "is_required": True, "is_conditional": False,
        "freshness_days": None,
        "requires_apostille": True, "apostille_countries": ["FR"],
        "requires_translation": True, "translation_languages": ["de"],
        "can_be_prefilled": False, "can_be_ocr_extracted": True,
        "typical_processing_days": 21, "book_early_flag": True,
        "book_early_reason": "Apostille + certified translation takes 3–4 weeks.",
        "success_tips": ["Include all academic transcripts."],
        "common_rejection_reasons": ["Unsigned or uncertified copies."],
        "form_url": None, "form_version": None,
    },
    {
        "corridor_from": "FR", "corridor_to": "DE", "visa_type": "skilled_worker",
        "employee_type": "any",
        "document_type": "biometric_photo",
        "document_name": "Biometric Passport Photos (2x)",
        "is_required": True, "is_conditional": False,
        "freshness_days": 90,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": False, "can_be_ocr_extracted": False,
        "typical_processing_days": 1, "book_early_flag": False,
        "success_tips": ["35mm × 45mm, white background, taken within 3 months."],
        "common_rejection_reasons": ["Non-white background."],
        "form_url": None, "form_version": None,
    },
    {
        "corridor_from": "FR", "corridor_to": "DE", "visa_type": "skilled_worker",
        "employee_type": "any",
        "document_type": "visa_application_form",
        "document_name": "National Visa Application Form (Type D)",
        "is_required": True, "is_conditional": False,
        "freshness_days": 90,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": True, "can_be_ocr_extracted": False,
        "typical_processing_days": 0, "book_early_flag": False,
        "success_tips": ["Complete online at videx-national.diplo.de"],
        "common_rejection_reasons": ["Incomplete travel history section."],
        "form_url": "https://videx-national.diplo.de/videx/visum-erfassung/",
        "form_version": "2024-01",
    },
    {
        "corridor_from": "FR", "corridor_to": "DE", "visa_type": "skilled_worker",
        "employee_type": "any",
        "document_type": "proof_of_accommodation",
        "document_name": "Proof of Accommodation in Germany",
        "is_required": True, "is_conditional": False,
        "freshness_days": 90,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": True, "translation_languages": ["de"],
        "can_be_prefilled": False, "can_be_ocr_extracted": False,
        "typical_processing_days": 3, "book_early_flag": False,
        "success_tips": ["Rental contract or employer housing letter."],
        "common_rejection_reasons": ["Document older than 3 months."],
        "form_url": None, "form_version": None,
    },

    # =========================================================================
    # FR → DE  |  posted_worker
    # =========================================================================
    {
        "corridor_from": "FR", "corridor_to": "DE", "visa_type": "posted_worker",
        "employee_type": "any",
        "document_type": "passport",
        "document_name": "Valid Passport",
        "is_required": True, "is_conditional": False,
        "freshness_days": None,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": False, "can_be_ocr_extracted": True,
        "typical_processing_days": 0, "book_early_flag": False,
        "success_tips": ["6 months validity required."],
        "common_rejection_reasons": [],
        "form_url": None, "form_version": None,
    },
    {
        "corridor_from": "FR", "corridor_to": "DE", "visa_type": "posted_worker",
        "employee_type": "any",
        "document_type": "a1_certificate",
        "document_name": "A1 Certificate (Social Security Posting)",
        "is_required": True, "is_conditional": False,
        "freshness_days": None,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": False, "can_be_ocr_extracted": False,
        "typical_processing_days": 14, "book_early_flag": True,
        "book_early_reason": "CPAM/URSSAF processing takes 1–3 weeks.",
        "success_tips": [
            "Apply via the employer's payroll provider or URSSAF portal.",
            "Required for any posting exceeding 8 days.",
            "Must be on-site and presented on request by German authorities.",
        ],
        "common_rejection_reasons": [
            "Certificate issued after posting start date.",
            "Employee name mismatch with passport.",
        ],
        "form_url": "https://www.urssaf.fr/portail/home/employeur/calculer-les-cotisations/les-elements-du-calcul/le-detachement-a-letranger.html",
        "form_version": None,
    },
    {
        "corridor_from": "FR", "corridor_to": "DE", "visa_type": "posted_worker",
        "employee_type": "any",
        "document_type": "posting_declaration",
        "document_name": "Posting Declaration (Make-it-in-Germany / Mindestlohn-Portal)",
        "is_required": True, "is_conditional": False,
        "freshness_days": None,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": True, "translation_languages": ["de"],
        "can_be_prefilled": True, "can_be_ocr_extracted": False,
        "typical_processing_days": 1, "book_early_flag": True,
        "book_early_reason": "Must be filed before the first working day in Germany.",
        "success_tips": [
            "File online at the German Customs Mindestlohn portal.",
            "Employer must confirm German minimum wage (Mindestlohn) will be paid.",
        ],
        "common_rejection_reasons": [
            "Declaration not filed before work commencement.",
        ],
        "form_url": "https://www.mindestlohn-meldepflicht.de",
        "form_version": None,
    },
    {
        "corridor_from": "FR", "corridor_to": "DE", "visa_type": "posted_worker",
        "employee_type": "any",
        "document_type": "employment_contract",
        "document_name": "Employment Contract / Assignment Letter",
        "is_required": True, "is_conditional": False,
        "freshness_days": 90,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": True, "translation_languages": ["de"],
        "can_be_prefilled": True, "can_be_ocr_extracted": False,
        "typical_processing_days": 3, "book_early_flag": False,
        "success_tips": [
            "Must specify posting duration, assignment location, and salary.",
        ],
        "common_rejection_reasons": [
            "Missing posting end date.",
            "Salary below Mindestlohn.",
        ],
        "form_url": None, "form_version": None,
    },

    # =========================================================================
    # UK → FR  |  long_stay_visa
    # =========================================================================
    {
        "corridor_from": "UK", "corridor_to": "FR", "visa_type": "long_stay_visa",
        "employee_type": "any",
        "document_type": "passport",
        "document_name": "Valid UK Passport or BRP",
        "is_required": True, "is_conditional": False,
        "freshness_days": None,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": False, "can_be_ocr_extracted": True,
        "typical_processing_days": 0, "book_early_flag": False,
        "success_tips": [
            "Must be valid for at least 3 months beyond intended stay.",
            "BRP holders must also carry their BRP card.",
        ],
        "common_rejection_reasons": ["Passport expiry within 3 months of stay."],
        "form_url": None, "form_version": None,
    },
    {
        "corridor_from": "UK", "corridor_to": "FR", "visa_type": "long_stay_visa",
        "employee_type": "any",
        "document_type": "visa_application_form",
        "document_name": "France-Visas Long-Stay Application",
        "is_required": True, "is_conditional": False,
        "freshness_days": 90,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": True, "can_be_ocr_extracted": False,
        "typical_processing_days": 0, "book_early_flag": False,
        "success_tips": [
            "Complete online at france-visas.gouv.fr",
            "Select 'Travailleur salarié' for employment-based applications.",
        ],
        "common_rejection_reasons": ["Wrong visa category selected."],
        "form_url": "https://france-visas.gouv.fr",
        "form_version": None,
    },
    {
        "corridor_from": "UK", "corridor_to": "FR", "visa_type": "long_stay_visa",
        "employee_type": "any",
        "document_type": "employment_contract",
        "document_name": "French Employment Contract",
        "is_required": True, "is_conditional": False,
        "freshness_days": 90,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": True, "can_be_ocr_extracted": False,
        "typical_processing_days": 5, "book_early_flag": False,
        "success_tips": [
            "Must be a French-law contract (CDI or CDD).",
            "Signed by both parties.",
        ],
        "common_rejection_reasons": ["UK-law contract submitted — French contract required."],
        "form_url": None, "form_version": None,
    },
    {
        "corridor_from": "UK", "corridor_to": "FR", "visa_type": "long_stay_visa",
        "employee_type": "any",
        "document_type": "ofii_work_authorisation",
        "document_name": "OFII Work Authorisation (from employer DIRECCTE filing)",
        "is_required": True, "is_conditional": False,
        "freshness_days": 90,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": False, "can_be_ocr_extracted": False,
        "typical_processing_days": 30, "book_early_flag": True,
        "book_early_reason": "DREETS/DIRECCTE approval takes 4–8 weeks.",
        "success_tips": [
            "Employer must apply to DREETS (ex-DIRECCTE) for the work authorisation.",
            "Employee cannot apply — this is an employer-initiated step.",
        ],
        "common_rejection_reasons": ["Employer did not file before visa application."],
        "form_url": None, "form_version": None,
    },
    {
        "corridor_from": "UK", "corridor_to": "FR", "visa_type": "long_stay_visa",
        "employee_type": "any",
        "document_type": "biometric_photo",
        "document_name": "Biometric Passport Photos (2x)",
        "is_required": True, "is_conditional": False,
        "freshness_days": 90,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": False, "can_be_ocr_extracted": False,
        "typical_processing_days": 1, "book_early_flag": False,
        "success_tips": ["35mm × 45mm, white background, taken within 6 months."],
        "common_rejection_reasons": ["Photo older than 6 months."],
        "form_url": None, "form_version": None,
    },

    # =========================================================================
    # UK → DE  |  skilled_worker
    # =========================================================================
    {
        "corridor_from": "UK", "corridor_to": "DE", "visa_type": "skilled_worker",
        "employee_type": "any",
        "document_type": "passport",
        "document_name": "Valid UK Passport",
        "is_required": True, "is_conditional": False,
        "freshness_days": None,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": False, "can_be_ocr_extracted": True,
        "typical_processing_days": 0, "book_early_flag": False,
        "success_tips": ["6 months validity beyond visa end date."],
        "common_rejection_reasons": [],
        "form_url": None, "form_version": None,
    },
    {
        "corridor_from": "UK", "corridor_to": "DE", "visa_type": "skilled_worker",
        "employee_type": "any",
        "document_type": "employment_contract",
        "document_name": "Employment Contract",
        "is_required": True, "is_conditional": False,
        "freshness_days": 90,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": True, "translation_languages": ["de"],
        "can_be_prefilled": True, "can_be_ocr_extracted": False,
        "typical_processing_days": 5, "book_early_flag": False,
        "success_tips": ["Salary must meet collective agreement for the profession."],
        "common_rejection_reasons": ["Salary below Tarifvertrag minimum."],
        "form_url": None, "form_version": None,
    },
    {
        "corridor_from": "UK", "corridor_to": "DE", "visa_type": "skilled_worker",
        "employee_type": "any",
        "document_type": "qualification_recognition",
        "document_name": "Proof of Qualification Recognition",
        "is_required": True, "is_conditional": False,
        "freshness_days": None,
        "requires_apostille": True, "apostille_countries": ["UK"],
        "requires_translation": True, "translation_languages": ["de"],
        "can_be_prefilled": False, "can_be_ocr_extracted": False,
        "typical_processing_days": 56, "book_early_flag": True,
        "book_early_reason": "UK apostille + ZAB recognition takes 6–10 weeks.",
        "success_tips": [
            "Post-Brexit: UK degrees require apostille from FCO.",
            "Apply for ZAB Statement of Comparability.",
        ],
        "common_rejection_reasons": ["No apostille post-Brexit."],
        "form_url": None, "form_version": None,
    },
    {
        "corridor_from": "UK", "corridor_to": "DE", "visa_type": "skilled_worker",
        "employee_type": "any",
        "document_type": "degree_certificate",
        "document_name": "Degree Certificate with Academic Transcripts",
        "is_required": True, "is_conditional": False,
        "freshness_days": None,
        "requires_apostille": True, "apostille_countries": ["UK"],
        "requires_translation": True, "translation_languages": ["de"],
        "can_be_prefilled": False, "can_be_ocr_extracted": True,
        "typical_processing_days": 21, "book_early_flag": True,
        "book_early_reason": "UK apostille processing time 4–6 weeks post-Brexit.",
        "success_tips": ["Apostille from FCDO (Foreign, Commonwealth & Development Office)."],
        "common_rejection_reasons": ["No FCDO apostille."],
        "form_url": None, "form_version": None,
    },
    {
        "corridor_from": "UK", "corridor_to": "DE", "visa_type": "skilled_worker",
        "employee_type": "any",
        "document_type": "visa_application_form",
        "document_name": "National Visa Application Form (Type D)",
        "is_required": True, "is_conditional": False,
        "freshness_days": 90,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": True, "can_be_ocr_extracted": False,
        "typical_processing_days": 0, "book_early_flag": False,
        "success_tips": ["Complete online at videx-national.diplo.de"],
        "common_rejection_reasons": [],
        "form_url": "https://videx-national.diplo.de/videx/visum-erfassung/",
        "form_version": "2024-01",
    },
    {
        "corridor_from": "UK", "corridor_to": "DE", "visa_type": "skilled_worker",
        "employee_type": "any",
        "document_type": "biometric_photo",
        "document_name": "Biometric Passport Photos (2x)",
        "is_required": True, "is_conditional": False,
        "freshness_days": 90,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": False, "can_be_ocr_extracted": False,
        "typical_processing_days": 1, "book_early_flag": False,
        "success_tips": ["35mm × 45mm, white background, within 3 months."],
        "common_rejection_reasons": [],
        "form_url": None, "form_version": None,
    },

    # =========================================================================
    # US → DE  |  blue_card
    # =========================================================================
    {
        "corridor_from": "US", "corridor_to": "DE", "visa_type": "blue_card",
        "employee_type": "any",
        "document_type": "passport",
        "document_name": "Valid US Passport",
        "is_required": True, "is_conditional": False,
        "freshness_days": None,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": False, "can_be_ocr_extracted": True,
        "typical_processing_days": 0, "book_early_flag": False,
        "success_tips": ["6 months validity beyond visa end date."],
        "common_rejection_reasons": [],
        "form_url": None, "form_version": None,
    },
    {
        "corridor_from": "US", "corridor_to": "DE", "visa_type": "blue_card",
        "employee_type": "any",
        "document_type": "degree_certificate",
        "document_name": "US University Degree (with apostille)",
        "is_required": True, "is_conditional": False,
        "freshness_days": None,
        "requires_apostille": True, "apostille_countries": ["US"],
        "requires_translation": True, "translation_languages": ["de"],
        "can_be_prefilled": False, "can_be_ocr_extracted": True,
        "typical_processing_days": 21, "book_early_flag": True,
        "book_early_reason": "State-level apostille + certified translation takes 3–5 weeks.",
        "success_tips": [
            "Apostille must be issued by the Secretary of State of the issuing state.",
            "Degree must appear in anabin as H+ or equivalent.",
            "Top-tier US universities (Ivy League, MIT, Stanford, etc.) are pre-approved.",
        ],
        "common_rejection_reasons": [
            "Federal apostille not accepted — must be state-level Secretary of State.",
        ],
        "form_url": None, "form_version": None,
    },
    {
        "corridor_from": "US", "corridor_to": "DE", "visa_type": "blue_card",
        "employee_type": "any",
        "document_type": "employment_contract",
        "document_name": "Employment Contract (€45,300+ salary)",
        "is_required": True, "is_conditional": False,
        "freshness_days": 90,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": True, "translation_languages": ["de"],
        "can_be_prefilled": True, "can_be_ocr_extracted": False,
        "typical_processing_days": 5, "book_early_flag": False,
        "success_tips": [
            "EUR salary equivalent must meet Blue Card minimum.",
            "If paid in USD, include conversion note at signing date exchange rate.",
        ],
        "common_rejection_reasons": ["USD salary not converted — consulate may reject."],
        "form_url": None, "form_version": None,
    },
    {
        "corridor_from": "US", "corridor_to": "DE", "visa_type": "blue_card",
        "employee_type": "any",
        "document_type": "visa_application_form",
        "document_name": "National Visa Application Form (Type D)",
        "is_required": True, "is_conditional": False,
        "freshness_days": 90,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": True, "can_be_ocr_extracted": False,
        "typical_processing_days": 0, "book_early_flag": False,
        "success_tips": ["Complete online. US citizens may enter Germany visa-free for 90 days and apply for Blue Card in-country."],
        "common_rejection_reasons": [],
        "form_url": "https://videx-national.diplo.de/videx/visum-erfassung/",
        "form_version": "2024-01",
    },
    {
        "corridor_from": "US", "corridor_to": "DE", "visa_type": "blue_card",
        "employee_type": "any",
        "document_type": "biometric_photo",
        "document_name": "Biometric Passport Photos (2x)",
        "is_required": True, "is_conditional": False,
        "freshness_days": 90,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": False, "can_be_ocr_extracted": False,
        "typical_processing_days": 1, "book_early_flag": False,
        "success_tips": ["35mm × 45mm, white background."],
        "common_rejection_reasons": [],
        "form_url": None, "form_version": None,
    },

    # =========================================================================
    # US → DE  |  skilled_worker
    # =========================================================================
    {
        "corridor_from": "US", "corridor_to": "DE", "visa_type": "skilled_worker",
        "employee_type": "any",
        "document_type": "passport",
        "document_name": "Valid US Passport",
        "is_required": True, "is_conditional": False,
        "freshness_days": None,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": False, "can_be_ocr_extracted": True,
        "typical_processing_days": 0, "book_early_flag": False,
        "success_tips": ["6 months validity beyond visa end date."],
        "common_rejection_reasons": [],
        "form_url": None, "form_version": None,
    },
    {
        "corridor_from": "US", "corridor_to": "DE", "visa_type": "skilled_worker",
        "employee_type": "any",
        "document_type": "employment_contract",
        "document_name": "Employment Contract",
        "is_required": True, "is_conditional": False,
        "freshness_days": 90,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": True, "translation_languages": ["de"],
        "can_be_prefilled": True, "can_be_ocr_extracted": False,
        "typical_processing_days": 5, "book_early_flag": False,
        "success_tips": ["Salary meets collective agreement for the occupation."],
        "common_rejection_reasons": [],
        "form_url": None, "form_version": None,
    },
    {
        "corridor_from": "US", "corridor_to": "DE", "visa_type": "skilled_worker",
        "employee_type": "any",
        "document_type": "qualification_recognition",
        "document_name": "Proof of US Qualification Recognition (ZAB)",
        "is_required": True, "is_conditional": False,
        "freshness_days": None,
        "requires_apostille": True, "apostille_countries": ["US"],
        "requires_translation": True, "translation_languages": ["de"],
        "can_be_prefilled": False, "can_be_ocr_extracted": False,
        "typical_processing_days": 56, "book_early_flag": True,
        "book_early_reason": "State apostille + ZAB recognition takes 6–10 weeks.",
        "success_tips": ["Apostille from Secretary of State of the issuing state."],
        "common_rejection_reasons": [],
        "form_url": None, "form_version": None,
    },
    {
        "corridor_from": "US", "corridor_to": "DE", "visa_type": "skilled_worker",
        "employee_type": "any",
        "document_type": "visa_application_form",
        "document_name": "National Visa Application Form (Type D)",
        "is_required": True, "is_conditional": False,
        "freshness_days": 90,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": True, "can_be_ocr_extracted": False,
        "typical_processing_days": 0, "book_early_flag": False,
        "success_tips": ["US citizens can also apply in-country (Ausländerbehörde) after 90-day visa-free entry."],
        "common_rejection_reasons": [],
        "form_url": "https://videx-national.diplo.de/videx/visum-erfassung/",
        "form_version": "2024-01",
    },

    # =========================================================================
    # IN → DE  |  skilled_worker  (BfA pre-approval required)
    # =========================================================================
    {
        "corridor_from": "IN", "corridor_to": "DE", "visa_type": "skilled_worker",
        "employee_type": "any",
        "document_type": "passport",
        "document_name": "Valid Indian Passport",
        "is_required": True, "is_conditional": False,
        "freshness_days": None,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": False, "can_be_ocr_extracted": True,
        "typical_processing_days": 0, "book_early_flag": False,
        "success_tips": [
            "6 months validity beyond visa end date.",
            "Ensure name matches degree certificates exactly — Indian names often differ across documents.",
        ],
        "common_rejection_reasons": ["Name inconsistency between passport and degree."],
        "form_url": None, "form_version": None,
    },
    {
        "corridor_from": "IN", "corridor_to": "DE", "visa_type": "skilled_worker",
        "employee_type": "any",
        "document_type": "bfa_pre_approval",
        "document_name": "Federal Employment Agency (BfA) Pre-Approval",
        "is_required": True, "is_conditional": False,
        "freshness_days": None,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": False, "can_be_ocr_extracted": False,
        "typical_processing_days": 30, "book_early_flag": True,
        "book_early_reason": "BfA Zustimmungsverfahren (Federal Employment Agency approval) takes 4–6 weeks and must happen before the visa appointment.",
        "success_tips": [
            "Employer submits to BfA via the ELAN-K2 portal (or local Ausländerbehörde for combined procedure).",
            "BfA checks: working conditions comparable to German workers, no preferred German candidates available.",
            "Combined procedure (beschleunigtes Fachkräfteverfahren) can reduce total timeline significantly.",
        ],
        "common_rejection_reasons": [
            "Employer did not file BfA approval before visa appointment.",
            "Salary below German collective agreement for the occupation.",
        ],
        "form_url": "https://con.arbeitsagentur.de/prod/elan/",
        "form_version": None,
    },
    {
        "corridor_from": "IN", "corridor_to": "DE", "visa_type": "skilled_worker",
        "employee_type": "any",
        "document_type": "employment_contract",
        "document_name": "Employment Contract",
        "is_required": True, "is_conditional": False,
        "freshness_days": 90,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": True, "translation_languages": ["de"],
        "can_be_prefilled": True, "can_be_ocr_extracted": False,
        "typical_processing_days": 5, "book_early_flag": False,
        "success_tips": [
            "Salary must meet collective agreement (Tarifvertrag) for the relevant occupation.",
            "Job title in contract must match the recognised qualification.",
        ],
        "common_rejection_reasons": ["Salary below Tarifvertrag minimum."],
        "form_url": None, "form_version": None,
    },
    {
        "corridor_from": "IN", "corridor_to": "DE", "visa_type": "skilled_worker",
        "employee_type": "any",
        "document_type": "degree_certificate",
        "document_name": "Indian Degree Certificate (with apostille or attested)",
        "is_required": True, "is_conditional": False,
        "freshness_days": None,
        "requires_apostille": True, "apostille_countries": ["IN"],
        "requires_translation": True, "translation_languages": ["de"],
        "can_be_prefilled": False, "can_be_ocr_extracted": True,
        "typical_processing_days": 28, "book_early_flag": True,
        "book_early_reason": "MEA apostille + certified translation takes 4–6 weeks.",
        "success_tips": [
            "Apostille from the Ministry of External Affairs (MEA), India.",
            "Degree must be assessed against anabin — many Indian technical universities are listed.",
            "IITs, NITs, and major universities are typically recognised.",
            "Include mark sheets (transcripts) for all years of study.",
        ],
        "common_rejection_reasons": [
            "MEA apostille missing.",
            "University not in anabin and no ZAB statement obtained.",
            "Missing mark sheets.",
        ],
        "form_url": "https://www.mea.gov.in/apostille.htm",
        "form_version": None,
    },
    {
        "corridor_from": "IN", "corridor_to": "DE", "visa_type": "skilled_worker",
        "employee_type": "any",
        "document_type": "visa_application_form",
        "document_name": "National Visa Application Form (Type D)",
        "is_required": True, "is_conditional": False,
        "freshness_days": 90,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": True, "can_be_ocr_extracted": False,
        "typical_processing_days": 0, "book_early_flag": False,
        "success_tips": ["Complete online. Book appointment at German consulate in Mumbai, Delhi, or Chennai."],
        "common_rejection_reasons": ["Wrong consulate jurisdiction — must apply in the state of residence."],
        "form_url": "https://videx-national.diplo.de/videx/visum-erfassung/",
        "form_version": "2024-01",
    },
    {
        "corridor_from": "IN", "corridor_to": "DE", "visa_type": "skilled_worker",
        "employee_type": "any",
        "document_type": "biometric_photo",
        "document_name": "Biometric Passport Photos (2x)",
        "is_required": True, "is_conditional": False,
        "freshness_days": 90,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": False, "can_be_ocr_extracted": False,
        "typical_processing_days": 1, "book_early_flag": False,
        "success_tips": ["35mm × 45mm, white background, taken within 3 months."],
        "common_rejection_reasons": [],
        "form_url": None, "form_version": None,
    },
    {
        "corridor_from": "IN", "corridor_to": "DE", "visa_type": "skilled_worker",
        "employee_type": "any",
        "document_type": "prior_visa_refusal_declaration",
        "document_name": "Prior Visa Refusal Declaration (if applicable)",
        "is_required": False, "is_conditional": True,
        "condition_expression": "prior_visa_refusals = true",
        "freshness_days": None,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": True, "translation_languages": ["de"],
        "can_be_prefilled": True, "can_be_ocr_extracted": False,
        "typical_processing_days": 3, "book_early_flag": False,
        "success_tips": [
            "Disclose ALL prior refusals — concealment is grounds for permanent ban.",
            "Prepare a cover letter explaining circumstances and changes since the refusal.",
        ],
        "common_rejection_reasons": ["Undisclosed prior refusal discovered during processing."],
        "form_url": None, "form_version": None,
    },

    # =========================================================================
    # IN → DE  |  blue_card
    # =========================================================================
    {
        "corridor_from": "IN", "corridor_to": "DE", "visa_type": "blue_card",
        "employee_type": "any",
        "document_type": "passport",
        "document_name": "Valid Indian Passport",
        "is_required": True, "is_conditional": False,
        "freshness_days": None,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": False, "can_be_ocr_extracted": True,
        "typical_processing_days": 0, "book_early_flag": False,
        "success_tips": ["6 months validity. Name must match degree certificates exactly."],
        "common_rejection_reasons": ["Name inconsistency."],
        "form_url": None, "form_version": None,
    },
    {
        "corridor_from": "IN", "corridor_to": "DE", "visa_type": "blue_card",
        "employee_type": "any",
        "document_type": "employment_contract",
        "document_name": "Employment Contract (€45,300+ salary)",
        "is_required": True, "is_conditional": False,
        "freshness_days": 90,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": True, "translation_languages": ["de"],
        "can_be_prefilled": True, "can_be_ocr_extracted": False,
        "typical_processing_days": 5, "book_early_flag": False,
        "success_tips": [
            "Blue Card requires gross annual salary ≥ €45,300 (general) or €41,042 (shortage occupation).",
            "Shortage occupations include IT, engineering, medical, and STEM fields.",
        ],
        "common_rejection_reasons": ["Salary below Blue Card minimum threshold."],
        "form_url": None, "form_version": None,
    },
    {
        "corridor_from": "IN", "corridor_to": "DE", "visa_type": "blue_card",
        "employee_type": "any",
        "document_type": "degree_certificate",
        "document_name": "Indian University Degree (with MEA apostille)",
        "is_required": True, "is_conditional": False,
        "freshness_days": None,
        "requires_apostille": True, "apostille_countries": ["IN"],
        "requires_translation": True, "translation_languages": ["de"],
        "can_be_prefilled": False, "can_be_ocr_extracted": True,
        "typical_processing_days": 28, "book_early_flag": True,
        "book_early_reason": "MEA apostille + ZAB recognition + translation takes 6–10 weeks.",
        "success_tips": [
            "Degree must be a 4-year programme minimum.",
            "IITs and NITs are recognised in anabin — attach printout.",
            "If not in anabin, apply for ZAB Statement of Comparability.",
        ],
        "common_rejection_reasons": [
            "3-year degree not equivalent to German 4-year requirement.",
            "MEA apostille missing.",
        ],
        "form_url": None, "form_version": None,
    },
    {
        "corridor_from": "IN", "corridor_to": "DE", "visa_type": "blue_card",
        "employee_type": "any",
        "document_type": "visa_application_form",
        "document_name": "National Visa Application Form (Type D)",
        "is_required": True, "is_conditional": False,
        "freshness_days": 90,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": True, "can_be_ocr_extracted": False,
        "typical_processing_days": 0, "book_early_flag": False,
        "success_tips": ["Complete online at videx-national.diplo.de"],
        "common_rejection_reasons": [],
        "form_url": "https://videx-national.diplo.de/videx/visum-erfassung/",
        "form_version": "2024-01",
    },
    {
        "corridor_from": "IN", "corridor_to": "DE", "visa_type": "blue_card",
        "employee_type": "any",
        "document_type": "biometric_photo",
        "document_name": "Biometric Passport Photos (2x)",
        "is_required": True, "is_conditional": False,
        "freshness_days": 90,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": False, "can_be_ocr_extracted": False,
        "typical_processing_days": 1, "book_early_flag": False,
        "success_tips": ["35mm × 45mm, white background."],
        "common_rejection_reasons": [],
        "form_url": None, "form_version": None,
    },

    # =========================================================================
    # FR → UK  |  skilled_worker
    # =========================================================================
    {
        "corridor_from": "FR", "corridor_to": "UK", "visa_type": "skilled_worker",
        "employee_type": "any",
        "document_type": "passport",
        "document_name": "Valid French Passport",
        "is_required": True, "is_conditional": False,
        "freshness_days": None,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": False, "can_be_ocr_extracted": True,
        "typical_processing_days": 0, "book_early_flag": False,
        "success_tips": ["Must be valid for the duration of the visa."],
        "common_rejection_reasons": [],
        "form_url": None, "form_version": None,
    },
    {
        "corridor_from": "FR", "corridor_to": "UK", "visa_type": "skilled_worker",
        "employee_type": "any",
        "document_type": "certificate_of_sponsorship",
        "document_name": "Certificate of Sponsorship (CoS) from UK employer",
        "is_required": True, "is_conditional": False,
        "freshness_days": 90,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": False, "can_be_ocr_extracted": False,
        "typical_processing_days": 14, "book_early_flag": True,
        "book_early_reason": "Employer must be a licensed sponsor and assign CoS before employee can apply.",
        "success_tips": [
            "Employer must hold a valid Skilled Worker sponsor licence.",
            "CoS must show SOC code, salary, and job title.",
            "Salary must be ≥ £26,200 or the 'going rate' for the occupation, whichever is higher.",
        ],
        "common_rejection_reasons": [
            "Employer not on Home Office sponsor register.",
            "Salary below going rate for the SOC code.",
            "CoS expired (valid 3 months from assignment).",
        ],
        "form_url": "https://www.gov.uk/skilled-worker-visa",
        "form_version": None,
    },
    {
        "corridor_from": "FR", "corridor_to": "UK", "visa_type": "skilled_worker",
        "employee_type": "any",
        "document_type": "english_language_proof",
        "document_name": "English Language Proficiency (B1 or above)",
        "is_required": True, "is_conditional": False,
        "freshness_days": None,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": False, "can_be_ocr_extracted": False,
        "typical_processing_days": 14, "book_early_flag": True,
        "book_early_reason": "IELTS/SELT test booking and results take 2–4 weeks.",
        "success_tips": [
            "Accepted: IELTS for UKVI (minimum B1), Trinity College SELT, or degree taught in English.",
            "French nationals are not automatically exempt — must demonstrate English proficiency.",
            "Degree taught in English: provide letter from university confirming medium of instruction.",
        ],
        "common_rejection_reasons": [
            "IELTS not approved 'for UKVI' — must be the secure English language test version.",
            "Test result older than 2 years.",
        ],
        "form_url": "https://www.gov.uk/english-language",
        "form_version": None,
    },
    {
        "corridor_from": "FR", "corridor_to": "UK", "visa_type": "skilled_worker",
        "employee_type": "any",
        "document_type": "biometric_photo",
        "document_name": "Digital Photo for UK Visa Application",
        "is_required": True, "is_conditional": False,
        "freshness_days": 30,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": False, "can_be_ocr_extracted": False,
        "typical_processing_days": 1, "book_early_flag": False,
        "success_tips": ["Upload digitally via the UK Visas and Immigration online portal."],
        "common_rejection_reasons": ["Photo uploaded late — must be before biometrics appointment."],
        "form_url": None, "form_version": None,
    },
    {
        "corridor_from": "FR", "corridor_to": "UK", "visa_type": "skilled_worker",
        "employee_type": "any",
        "document_type": "tuberculosis_test",
        "document_name": "Tuberculosis Test Certificate",
        "is_required": True, "is_conditional": False,
        "freshness_days": 180,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": False, "can_be_ocr_extracted": False,
        "typical_processing_days": 5, "book_early_flag": True,
        "book_early_reason": "Must be done at an UKVI-approved clinic; results take 3–7 days.",
        "success_tips": [
            "Required for stays over 6 months.",
            "Must be from a Home Office approved clinic in France.",
            "Valid for 6 months from test date.",
        ],
        "common_rejection_reasons": [
            "Test conducted at non-approved clinic.",
            "Certificate expired (>6 months old).",
        ],
        "form_url": "https://www.gov.uk/tb-test-visa",
        "form_version": None,
    },

    # =========================================================================
    # DE → UK  |  skilled_worker
    # =========================================================================
    {
        "corridor_from": "DE", "corridor_to": "UK", "visa_type": "skilled_worker",
        "employee_type": "any",
        "document_type": "passport",
        "document_name": "Valid German Passport",
        "is_required": True, "is_conditional": False,
        "freshness_days": None,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": False, "can_be_ocr_extracted": True,
        "typical_processing_days": 0, "book_early_flag": False,
        "success_tips": ["Must be valid for the duration of the visa."],
        "common_rejection_reasons": [],
        "form_url": None, "form_version": None,
    },
    {
        "corridor_from": "DE", "corridor_to": "UK", "visa_type": "skilled_worker",
        "employee_type": "any",
        "document_type": "certificate_of_sponsorship",
        "document_name": "Certificate of Sponsorship (CoS)",
        "is_required": True, "is_conditional": False,
        "freshness_days": 90,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": False, "can_be_ocr_extracted": False,
        "typical_processing_days": 14, "book_early_flag": True,
        "book_early_reason": "Employer must assign CoS before employee application.",
        "success_tips": [
            "Salary ≥ £26,200 or going rate for SOC code.",
            "German nationals eligible for UK Skilled Worker — not visa-free for work post-Brexit.",
        ],
        "common_rejection_reasons": ["Employer not licensed as sponsor."],
        "form_url": "https://www.gov.uk/skilled-worker-visa",
        "form_version": None,
    },
    {
        "corridor_from": "DE", "corridor_to": "UK", "visa_type": "skilled_worker",
        "employee_type": "any",
        "document_type": "tuberculosis_test",
        "document_name": "Tuberculosis Test Certificate",
        "is_required": True, "is_conditional": False,
        "freshness_days": 180,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": False, "can_be_ocr_extracted": False,
        "typical_processing_days": 5, "book_early_flag": True,
        "book_early_reason": "Must be at UKVI-approved clinic in Germany.",
        "success_tips": ["Clinics in Berlin, Frankfurt, Munich are UKVI-approved. Book early."],
        "common_rejection_reasons": ["Non-approved clinic used."],
        "form_url": "https://www.gov.uk/tb-test-visa",
        "form_version": None,
    },
    {
        "corridor_from": "DE", "corridor_to": "UK", "visa_type": "skilled_worker",
        "employee_type": "any",
        "document_type": "english_language_proof",
        "document_name": "English Language Proficiency (B1 minimum)",
        "is_required": True, "is_conditional": False,
        "freshness_days": None,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": False, "can_be_ocr_extracted": False,
        "typical_processing_days": 14, "book_early_flag": True,
        "book_early_reason": "IELTS for UKVI test booking and results take 2–4 weeks.",
        "success_tips": [
            "English-taught university degree can exempt this requirement.",
            "IELTS minimum: 4.0 in each component for B1.",
        ],
        "common_rejection_reasons": ["Regular IELTS accepted — must be 'for UKVI' version."],
        "form_url": None, "form_version": None,
    },
    {
        "corridor_from": "DE", "corridor_to": "UK", "visa_type": "skilled_worker",
        "employee_type": "any",
        "document_type": "biometric_photo",
        "document_name": "Digital Photo",
        "is_required": True, "is_conditional": False,
        "freshness_days": 30,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": False, "can_be_ocr_extracted": False,
        "typical_processing_days": 1, "book_early_flag": False,
        "success_tips": ["Upload via UKVI online portal."],
        "common_rejection_reasons": [],
        "form_url": None, "form_version": None,
    },

    # =========================================================================
    # FR → US  |  l1_visa
    # =========================================================================
    {
        "corridor_from": "FR", "corridor_to": "US", "visa_type": "l1_visa",
        "employee_type": "any",
        "document_type": "passport",
        "document_name": "Valid French Passport",
        "is_required": True, "is_conditional": False,
        "freshness_days": None,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": False, "can_be_ocr_extracted": True,
        "typical_processing_days": 0, "book_early_flag": False,
        "success_tips": ["Must be valid at least 6 months beyond intended US stay."],
        "common_rejection_reasons": [],
        "form_url": None, "form_version": None,
    },
    {
        "corridor_from": "FR", "corridor_to": "US", "visa_type": "l1_visa",
        "employee_type": "any",
        "document_type": "i_129_petition",
        "document_name": "USCIS I-129 Petition Approval Notice",
        "is_required": True, "is_conditional": False,
        "freshness_days": None,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": False, "can_be_ocr_extracted": False,
        "typical_processing_days": 90, "book_early_flag": True,
        "book_early_reason": "USCIS I-129 standard processing: 3–6 months. Premium processing (I-907): 15 business days.",
        "success_tips": [
            "Employer (US entity) files I-129 with USCIS.",
            "Premium processing (Form I-907, $2,805 fee) reduces to 15 business days.",
            "L-1A (managers/executives) vs L-1B (specialized knowledge) — ensure correct category.",
            "Employee must have worked for affiliated entity for 1 year within last 3 years.",
        ],
        "common_rejection_reasons": [
            "RFE (Request for Evidence) for specialized knowledge — must document unique expertise.",
            "Less than 1 year qualifying employment at foreign entity.",
            "Blanket L petition not used when individual petition required.",
        ],
        "form_url": "https://www.uscis.gov/i-129",
        "form_version": "I-129 (12/15/23)",
    },
    {
        "corridor_from": "FR", "corridor_to": "US", "visa_type": "l1_visa",
        "employee_type": "any",
        "document_type": "ds_160",
        "document_name": "DS-160 Nonimmigrant Visa Application",
        "is_required": True, "is_conditional": False,
        "freshness_days": 90,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": True, "can_be_ocr_extracted": False,
        "typical_processing_days": 1, "book_early_flag": False,
        "success_tips": [
            "Complete online at ceac.state.gov",
            "Print confirmation page (barcode) for interview.",
            "Social media handles for last 5 years required.",
        ],
        "common_rejection_reasons": [
            "Incomplete social media section.",
            "Travel history inconsistencies.",
        ],
        "form_url": "https://ceac.state.gov/genniv/",
        "form_version": "DS-160",
    },
    {
        "corridor_from": "FR", "corridor_to": "US", "visa_type": "l1_visa",
        "employee_type": "any",
        "document_type": "employment_letter",
        "document_name": "Employer Support Letter (French and US entities)",
        "is_required": True, "is_conditional": False,
        "freshness_days": 90,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": True, "can_be_ocr_extracted": False,
        "typical_processing_days": 5, "book_early_flag": False,
        "success_tips": [
            "Letter from French entity confirming 1+ year of qualifying employment.",
            "Letter from US entity confirming role, salary, and start date.",
            "Both letters must be on company letterhead, signed by authorised signatory.",
        ],
        "common_rejection_reasons": [
            "Letter not on company letterhead.",
            "Qualifying employment period not clearly stated.",
        ],
        "form_url": None, "form_version": None,
    },
    {
        "corridor_from": "FR", "corridor_to": "US", "visa_type": "l1_visa",
        "employee_type": "any",
        "document_type": "biometric_photo",
        "document_name": "US Visa Photo (2x, 2x2 inches)",
        "is_required": True, "is_conditional": False,
        "freshness_days": 90,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": False, "can_be_ocr_extracted": False,
        "typical_processing_days": 1, "book_early_flag": False,
        "success_tips": [
            "2×2 inches (51×51mm), white background.",
            "Taken within 6 months.",
            "Head must be between 1–1⅜ inches from chin to top of head.",
        ],
        "common_rejection_reasons": ["Photo size non-standard (US requires 2×2 inches, not 35×45mm)."],
        "form_url": None, "form_version": None,
    },

    # =========================================================================
    # FR → US  |  o1_visa
    # =========================================================================
    {
        "corridor_from": "FR", "corridor_to": "US", "visa_type": "o1_visa",
        "employee_type": "any",
        "document_type": "passport",
        "document_name": "Valid French Passport",
        "is_required": True, "is_conditional": False,
        "freshness_days": None,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": False, "can_be_ocr_extracted": True,
        "typical_processing_days": 0, "book_early_flag": False,
        "success_tips": ["6 months validity beyond intended US stay."],
        "common_rejection_reasons": [],
        "form_url": None, "form_version": None,
    },
    {
        "corridor_from": "FR", "corridor_to": "US", "visa_type": "o1_visa",
        "employee_type": "any",
        "document_type": "i_129_petition",
        "document_name": "USCIS I-129 Petition (O-1 category) Approval Notice",
        "is_required": True, "is_conditional": False,
        "freshness_days": None,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": False, "can_be_ocr_extracted": False,
        "typical_processing_days": 90, "book_early_flag": True,
        "book_early_reason": "USCIS I-129 (O-1) standard: 3–6 months. Premium processing: 15 business days.",
        "success_tips": [
            "O-1A (extraordinary ability in business/science/education/athletics) vs O-1B (arts/film).",
            "Must demonstrate extraordinary ability via at least 3 of 8 USCIS criteria.",
            "Evidence: awards, publications, judging, high salary, critical role, press coverage, contributions, memberships.",
            "Peer review letters from recognised experts in the field strengthen the petition significantly.",
        ],
        "common_rejection_reasons": [
            "Insufficient evidence of extraordinary ability — must meet 3+ criteria.",
            "Generic reference letters without specifics about the petitioner's achievements.",
        ],
        "form_url": "https://www.uscis.gov/i-129",
        "form_version": "I-129 (12/15/23)",
    },
    {
        "corridor_from": "FR", "corridor_to": "US", "visa_type": "o1_visa",
        "employee_type": "any",
        "document_type": "peer_review_letters",
        "document_name": "Expert Peer Review / Reference Letters",
        "is_required": True, "is_conditional": False,
        "freshness_days": 90,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": ["en"],
        "can_be_prefilled": False, "can_be_ocr_extracted": False,
        "typical_processing_days": 21, "book_early_flag": True,
        "book_early_reason": "Collecting expert letters from recognised authorities takes 3–6 weeks.",
        "success_tips": [
            "3–5 expert letters from industry-recognised authorities.",
            "Letters must be specific about the petitioner's extraordinary contributions.",
            "Signatories must have demonstrable credentials in the field.",
            "Generic letters ('I have known X for Y years and they are excellent') are insufficient.",
        ],
        "common_rejection_reasons": ["Vague letters without specific achievement citations."],
        "form_url": None, "form_version": None,
    },
    {
        "corridor_from": "FR", "corridor_to": "US", "visa_type": "o1_visa",
        "employee_type": "any",
        "document_type": "ds_160",
        "document_name": "DS-160 Nonimmigrant Visa Application",
        "is_required": True, "is_conditional": False,
        "freshness_days": 90,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": True, "can_be_ocr_extracted": False,
        "typical_processing_days": 1, "book_early_flag": False,
        "success_tips": ["Complete at ceac.state.gov. Print barcode confirmation page."],
        "common_rejection_reasons": [],
        "form_url": "https://ceac.state.gov/genniv/",
        "form_version": "DS-160",
    },
    {
        "corridor_from": "FR", "corridor_to": "US", "visa_type": "o1_visa",
        "employee_type": "any",
        "document_type": "achievement_evidence",
        "document_name": "Achievement Evidence Portfolio",
        "is_required": True, "is_conditional": False,
        "freshness_days": None,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": ["en"],
        "can_be_prefilled": False, "can_be_ocr_extracted": False,
        "typical_processing_days": 14, "book_early_flag": True,
        "book_early_reason": "Compiling awards, press, publications, salary evidence takes 2–4 weeks.",
        "success_tips": [
            "Compile: awards, press articles, patents, publications, salary comparisons, conference invitations, judging roles.",
            "Organise into tabbed exhibit binder — USCIS officers appreciate clear evidence structure.",
            "Salary comparisons: show petitioner earns significantly above peers in the field.",
        ],
        "common_rejection_reasons": [
            "Missing salary evidence.",
            "Press articles not translated to English.",
        ],
        "form_url": None, "form_version": None,
    },

    # =========================================================================
    # UK → DE  |  blue_card  (brief — reuses UK→DE passport + supplements)
    # =========================================================================
    {
        "corridor_from": "UK", "corridor_to": "DE", "visa_type": "blue_card",
        "employee_type": "any",
        "document_type": "passport",
        "document_name": "Valid UK Passport",
        "is_required": True, "is_conditional": False,
        "freshness_days": None,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": False, "can_be_ocr_extracted": True,
        "typical_processing_days": 0, "book_early_flag": False,
        "success_tips": ["6 months validity beyond visa end date."],
        "common_rejection_reasons": [],
        "form_url": None, "form_version": None,
    },
    {
        "corridor_from": "UK", "corridor_to": "DE", "visa_type": "blue_card",
        "employee_type": "any",
        "document_type": "employment_contract",
        "document_name": "Employment Contract (€45,300+ gross annual salary)",
        "is_required": True, "is_conditional": False,
        "freshness_days": 90,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": True, "translation_languages": ["de"],
        "can_be_prefilled": True, "can_be_ocr_extracted": False,
        "typical_processing_days": 5, "book_early_flag": False,
        "success_tips": ["Salary meets or exceeds €45,300 Blue Card minimum."],
        "common_rejection_reasons": ["Salary in GBP not converted to EUR — consulate may reject."],
        "form_url": None, "form_version": None,
    },
    {
        "corridor_from": "UK", "corridor_to": "DE", "visa_type": "blue_card",
        "employee_type": "any",
        "document_type": "degree_certificate",
        "document_name": "UK University Degree (with FCDO apostille)",
        "is_required": True, "is_conditional": False,
        "freshness_days": None,
        "requires_apostille": True, "apostille_countries": ["UK"],
        "requires_translation": True, "translation_languages": ["de"],
        "can_be_prefilled": False, "can_be_ocr_extracted": True,
        "typical_processing_days": 21, "book_early_flag": True,
        "book_early_reason": "FCDO apostille post-Brexit takes 4–6 weeks.",
        "success_tips": [
            "UK universities (Russell Group) are well-represented in anabin.",
            "FCDO apostille required post-Brexit — no longer automatically recognised.",
        ],
        "common_rejection_reasons": ["No FCDO apostille post-Brexit.", "University not in anabin — ZAB statement needed."],
        "form_url": None, "form_version": None,
    },
    {
        "corridor_from": "UK", "corridor_to": "DE", "visa_type": "blue_card",
        "employee_type": "any",
        "document_type": "visa_application_form",
        "document_name": "National Visa Application Form (Type D)",
        "is_required": True, "is_conditional": False,
        "freshness_days": 90,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": True, "can_be_ocr_extracted": False,
        "typical_processing_days": 0, "book_early_flag": False,
        "success_tips": ["Complete at videx-national.diplo.de"],
        "common_rejection_reasons": [],
        "form_url": "https://videx-national.diplo.de/videx/visum-erfassung/",
        "form_version": "2024-01",
    },
    {
        "corridor_from": "UK", "corridor_to": "DE", "visa_type": "blue_card",
        "employee_type": "any",
        "document_type": "biometric_photo",
        "document_name": "Biometric Passport Photos (2x)",
        "is_required": True, "is_conditional": False,
        "freshness_days": 90,
        "requires_apostille": False, "apostille_countries": [],
        "requires_translation": False, "translation_languages": [],
        "can_be_prefilled": False, "can_be_ocr_extracted": False,
        "typical_processing_days": 1, "book_early_flag": False,
        "success_tips": ["35mm × 45mm, white background."],
        "common_rejection_reasons": [],
        "form_url": None, "form_version": None,
    },
]


# ---------------------------------------------------------------------------
# Upsert logic
# ---------------------------------------------------------------------------

def _json_or_none(value):
    """Return JSON string for lists, or None for empty/None."""
    if value is None or value == []:
        return None
    return json.dumps(value)


def seed(dry_run: bool = False) -> int:
    """
    Insert all requirement rows. Returns the count of rows upserted.
    Safe to re-run — uses INSERT ... ON CONFLICT DO NOTHING.
    """
    session = SessionLocal()
    inserted = 0
    skipped = 0

    try:
        for row in REQUIREMENTS:
            params = {
                "corridor_from": row["corridor_from"],
                "corridor_to": row["corridor_to"],
                "visa_type": row["visa_type"],
                "employee_type": row.get("employee_type", "any"),
                "document_type": row["document_type"],
                "document_name": row["document_name"],
                "is_required": row.get("is_required", True),
                "is_conditional": row.get("is_conditional", False),
                "condition_expression": row.get("condition_expression"),
                "freshness_days": row.get("freshness_days"),
                "requires_apostille": row.get("requires_apostille", False),
                "apostille_countries": _json_or_none(row.get("apostille_countries")),
                "requires_translation": row.get("requires_translation", False),
                "translation_languages": _json_or_none(row.get("translation_languages")),
                "can_be_prefilled": row.get("can_be_prefilled", False),
                "can_be_ocr_extracted": row.get("can_be_ocr_extracted", False),
                "typical_processing_days": row.get("typical_processing_days"),
                "book_early_flag": row.get("book_early_flag", False),
                "book_early_reason": row.get("book_early_reason"),
                "success_tips": _json_or_none(row.get("success_tips")),
                "common_rejection_reasons": _json_or_none(row.get("common_rejection_reasons")),
                "form_url": row.get("form_url"),
                "form_version": row.get("form_version"),
            }

            if dry_run:
                log.info("[DRY RUN] Would insert: %s/%s/%s/%s",
                         params["corridor_from"], params["corridor_to"],
                         params["visa_type"], params["document_type"])
                inserted += 1
                continue

            result = session.execute(
                text("""
                    INSERT INTO public.immigration_requirements (
                        corridor_from, corridor_to, visa_type, employee_type,
                        document_type, document_name,
                        is_required, is_conditional, condition_expression,
                        freshness_days, requires_apostille, apostille_countries,
                        requires_translation, translation_languages,
                        can_be_prefilled, can_be_ocr_extracted,
                        typical_processing_days, book_early_flag, book_early_reason,
                        success_tips, common_rejection_reasons,
                        form_url, form_version
                    ) VALUES (
                        :corridor_from, :corridor_to, :visa_type, :employee_type,
                        :document_type, :document_name,
                        :is_required, :is_conditional, :condition_expression,
                        :freshness_days, :requires_apostille, :apostille_countries::jsonb,
                        :requires_translation, :translation_languages::jsonb,
                        :can_be_prefilled, :can_be_ocr_extracted,
                        :typical_processing_days, :book_early_flag, :book_early_reason,
                        :success_tips::jsonb, :common_rejection_reasons::jsonb,
                        :form_url, :form_version
                    )
                    ON CONFLICT (corridor_from, corridor_to, visa_type, employee_type, document_type)
                    DO NOTHING
                """),
                params,
            )
            if result.rowcount > 0:
                inserted += 1
            else:
                skipped += 1

        if not dry_run:
            session.commit()
            log.info("[seed] Inserted %d rows, skipped %d (already existed)", inserted, skipped)
        return inserted

    except Exception as exc:
        session.rollback()
        log.error("[seed] Failed: %s", exc)
        raise
    finally:
        session.close()


if __name__ == "__main__":
    import argparse

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")

    parser = argparse.ArgumentParser(description="Seed immigration requirements data")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print what would be inserted without writing to DB")
    args = parser.parse_args()

    count = seed(dry_run=args.dry_run)
    print(f"Done — {count} row(s) {'would be ' if args.dry_run else ''}inserted.")
