#!/usr/bin/env python3
"""Fact-dictionary coverage & drift audit (form-fill integration, Build B instrument).

The governed fact vocabulary lives in ``backend/app/services/fact_dictionary.py`` (the
FR→NO seed the spec §7 endorses). To *scale* it to every corridor we need to see, concretely:

  1. COVERAGE  — which real form fields (``form_field_mappings.vault_field_path``) have no
     governing ``FactEntry`` yet, so a form can't resolve a value for them.
  2. DRIFT     — where the registry's ``prefill_source`` vocabulary and the mappings' vault
     paths disagree on the join key (the plan's integration hazard #1). If they drift, a
     value captured once will NOT fill the next form.
  3. FIREWALL  — the harvested consult-professional signal (corridor-content) vs the facts
     actually flagged ``professional_review_required`` in the registry.

This is a read-only diagnostic (no code/behaviour change). It writes a report so the
expansion of the dictionary is a scoped data task, not guesswork.

Usage:  python3 scripts/fact_dictionary_coverage.py            # print report
        python3 scripts/fact_dictionary_coverage.py --write    # also write docs/plans/fact-dictionary-coverage.md
"""
from __future__ import annotations
import json, re, sys, glob, os
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SEED = ROOT / "supabase" / "migrations" / "20260605800000_imm11_form_field_mappings_seed.sql"
CC_DIR = ROOT / "data" / "corridor-content"
REPORT = ROOT / "docs" / "plans" / "fact-dictionary-coverage.md"

sys.path.insert(0, str(ROOT))
from backend.app.services import fact_dictionary as fd  # noqa: E402


def _mapping_fields():
    """(form_field_key, vault_field_path) pairs from the form_field_mappings seed."""
    if not SEED.exists():
        return []
    text = SEED.read_text(encoding="utf-8")
    return re.findall(
        r"'([a-z0-9_]+)'\s*,\s*'[^']+'\s*,\s*'([a-z0-9_]+)'\s*,\s*(?:NULL|'[^']*')\s*,\s*(?:TRUE|FALSE)",
        text, re.I,
    )


def _resolves(vault_path: str, field_key: str) -> bool:
    """Does the registry govern this form field, by prefill_source tail or by field_id?"""
    for f in fd._FACTS:
        if f.prefill_source and f.prefill_source.split(".")[-1] == vault_path:
            return True
        if field_key in f.field_ids or vault_path in f.field_ids:
            return True
    return False


def build_report() -> str:
    facts = fd._FACTS
    firewall = [f for f in facts if f.professional_review_required]
    src_prefixes = Counter(f.prefill_source.split(".")[0] for f in facts if f.prefill_source)

    pairs = _mapping_fields()
    vault_paths = sorted(set(v for _, v in pairs))
    covered = [v for v in vault_paths if any(_resolves(v, k) for k, vv in pairs if vv == v)]
    gaps = [v for v in vault_paths if v not in covered]

    # drift: vault paths that share a *concept* with a registry fact under a different key
    reg_tails = {f.prefill_source.split(".")[-1] for f in facts if f.prefill_source}
    drift = []
    for v in vault_paths:
        if v in reg_tails:
            continue
        # crude concept overlap on the leading token
        stem = v.split("_")[0]
        near = sorted(t for t in reg_tails if t.startswith(stem) or stem in t)
        if near:
            drift.append((v, near))

    # corridor-content consult-professional signal
    cc_prof = Counter()
    cc_total = 0
    for f in CC_DIR.glob("*.ndjson"):
        for line in f.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line:
                continue
            r = json.loads(line)
            cc_total += 1
            if r.get("consult_professional"):
                cc_prof[f.stem] += 1

    L = []
    L.append("# Fact-dictionary coverage & drift audit\n")
    L.append("_Generated by `scripts/fact_dictionary_coverage.py` — read-only diagnostic for "
             "Build B of [the form-fill integration plan](form-fill-integration-build-plan.md)._\n")
    L.append("## Registry state\n")
    L.append(f"- Governed facts: **{len(facts)}** ({len(firewall)} consult-professional / never-filled).")
    L.append(f"- `prefill_source` prefixes in use: {dict(src_prefixes)} (+ {sum(1 for f in facts if not f.prefill_source)} with no source).\n")

    L.append("## 1. Form-field coverage\n")
    L.append(f"Real form fields in `form_field_mappings`: **{len(vault_paths)}** distinct vault paths. "
             f"Governed by a fact today: **{len(covered)}**. Not yet governed: **{len(gaps)}**.\n")
    if gaps:
        L.append("| vault_field_path | status |\n|---|---|")
        for v in gaps:
            L.append(f"| `{v}` | ❌ no governing FactEntry — a form using it can't resolve a value |")
        L.append("")

    L.append("## 2. Join-key drift (integration hazard #1)\n")
    if drift:
        L.append("The registry names a fact one way; the form mapping names the same concept another. "
                 "Until reconciled, a value captured once will **not** fill the other form.\n")
        L.append("| form mapping vault path | nearest registry source key | note |\n|---|---|---|")
        for v, near in drift:
            L.append(f"| `{v}` | `{', '.join(near)}` | reconcile onto one canonical key |")
        L.append("")
    else:
        L.append("No obvious concept drift detected between the mapping vault paths and the registry keys.\n")
    L.append("> Also note the **prefix mismatch**: the registry resolves via `prefill_source` prefixes "
             "(`profile.`/`contract.`/`case.`) while `form_field_mappings.vault_field_path` are bare "
             "`imm_employee_profiles` columns. The prefill ladder must map one to the other, or the join breaks.\n")

    L.append("## 3. Consult-professional firewall — demand vs. coverage\n")
    L.append(f"Corridor-content carries **{sum(cc_prof.values())}** consult-professional steps across "
             f"**{len(cc_prof)}** corridors (of {cc_total} total records). The registry firewalls "
             f"**{len(firewall)}** facts today ({', '.join(f.fact_key for f in firewall)}).\n")
    L.append("These are different layers — corridor-content flags *steps*, the registry flags *fields* — "
             "but the firewall must be enforced wherever a regulated field is auto-fillable. As field "
             "facts are added for new corridors, each regulated one must inherit `professional_review_required=True`.\n")

    L.append("## Next actions\n")
    L.append("1. Reconcile the join key: one canonical name per fact, mapped to both the prefill "
             "`prefill_source` and the `vault_field_path` (close §2).\n")
    L.append(f"2. Add FactEntry rows for the {len(gaps)} uncovered form fields (close §1).\n")
    L.append("3. Keep this audit green in CI so the dictionary can't silently drift as corridors are added.\n")
    return "\n".join(L) + "\n"


def main():
    report = build_report()
    if "--write" in sys.argv:
        REPORT.write_text(report, encoding="utf-8")
        print(f"WROTE {REPORT.relative_to(ROOT)}")
    else:
        print(report)


if __name__ == "__main__":
    main()
