#!/usr/bin/env python3
"""Form-acquisition worklist from the corridor-content harvest (form-fill Build A / plan §3.1).

The harvested corridor-content `form_name` field is the authoritative list of which forms each
corridor needs. This turns it into a prioritised acquisition backlog: the distinct
(country_iso, form_name, authority, source_url) forms across all corridors, classified by whether
they are plausibly a **fillable PDF** worth acquiring (like the France-Visas CERFA — the one real
AcroForm found so far, docs/form-autofill/ACROFORM-FEASIBILITY-DE-FR.md) or an **online portal /
notification** with no blank PDF to fill.

Read-only: reads data/corridor-content/*.ndjson, writes docs/form-autofill/form-acquisition-worklist.md.

Usage:  python3 scripts/form_acquisition_worklist.py           # print the report
        python3 scripts/form_acquisition_worklist.py --write   # also write the doc
"""
from __future__ import annotations
import glob
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CC_DIR = ROOT / "data" / "corridor-content"
REPORT = ROOT / "docs" / "form-autofill" / "form-acquisition-worklist.md"

# An online portal / app / e-filing flow — there is no blank PDF to pre-fill (an INPUT captured
# online), so it is out of scope for AcroForm fill (FINDINGS.md Appendix A.1 / the DE VIDEX case).
_PORTAL = re.compile(
    r"\b(portal|online|e-?fil|e-?frro|digital|\bapp\b|web|self-?service|myaccount|"
    r"tastselv|altinn|hikorea|absher|metrash|hukoomi|digid|epos|idse|anef|gov\.br|"
    r"mon portail|\bsua\b|idnr|e-?visa|calculator|compass)\b",
    re.I,
)
# A named, coded government form — a form code is a strong signal a real blank PDF exists to fill.
_CODED = re.compile(
    r"\b("
    r"NAT ?\d{3,}|EX-?\d+|BI-?\d+|DHA-?\d+|DS-?\d+|RF-?\d+|PIT-?\d+|CA\d{3,}|EMP\d{3,}|"
    r"TM\.?\d+|WP\.?\d+|IR\d{2,}|BIR\d+|IR56[A-Z]|Form ?\d+|Form ?[A-Z]\d?|Annexe ?\d+|"
    r"Bijlage ?\d+|CERFA|MFin ?\d+|IRP3|IR21|Form ?11|Form ?12"
    r")\b",
    re.I,
)


def _rows():
    for f in sorted(CC_DIR.glob("*.ndjson")):
        iso = f.stem
        for line in f.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line:
                continue
            r = json.loads(line)
            fn = r.get("form_name")
            if fn:
                yield iso, fn.strip(), (r.get("authority") or ""), (r.get("source_url") or "")


def _classify(form_name: str) -> str:
    if _PORTAL.search(form_name):
        return "portal"
    if _CODED.search(form_name):
        return "coded_pdf"
    return "other"


def build_report() -> str:
    # dedupe by (iso, form_name); keep first authority/source_url seen
    seen: dict[tuple[str, str], tuple[str, str]] = {}
    per_corridor = defaultdict(set)
    for iso, fn, authority, src in _rows():
        per_corridor[iso].add(fn)
        seen.setdefault((iso, fn), (authority, src))

    klass = defaultdict(list)
    for (iso, fn), (authority, src) in sorted(seen.items()):
        klass[_classify(fn)].append((iso, fn, authority, src))

    n_total = len(seen)
    n_coded = len(klass["coded_pdf"])
    n_portal = len(klass["portal"])
    n_other = len(klass["other"])

    L: list[str] = []
    L.append("# Form-acquisition worklist (from the corridor-content harvest)\n")
    L.append("_Generated by `scripts/form_acquisition_worklist.py` — the plan's Build A §3.1 backlog "
             "([form-fill integration plan](../plans/form-fill-integration-build-plan.md)). "
             "The harvested `form_name` field is the authoritative list of forms each corridor needs._\n")
    L.append("## Summary\n")
    L.append(f"- **{n_total}** distinct (corridor, form) pairs across **{len(per_corridor)}** corridors.")
    L.append(f"- **{n_coded}** look like a **coded government PDF** (a form code → a blank PDF may exist to fill) — the acquisition candidates.")
    L.append(f"- **{n_portal}** are **online portals / e-filing / apps** — no blank PDF to pre-fill (out of scope for AcroForm fill).")
    L.append(f"- **{n_other}** are un-coded / generic (bank KYC, \"varies by provider\", notifications) — assess case by case.\n")
    L.append("> Classification is heuristic (keyword-based) and only narrows the search — a coded name is not proof "
             "of a fillable AcroForm (most gov PDFs are flattened; France's CERFA `*05` was the one fillable one of "
             "five checked). Each candidate still needs the AcroForm check from ACROFORM-FEASIBILITY-DE-FR.md, "
             "fetched in a real browser. **Exemplar done:** `FR_cerfa_14571_v2024` (France-Visas CERFA 14571-*05).\n")

    L.append("## Coded-PDF acquisition candidates\n")
    L.append("| corridor | form | authority |\n|---|---|---|")
    for iso, fn, authority, _src in klass["coded_pdf"]:
        fn_s = fn if len(fn) <= 90 else fn[:87] + "…"
        L.append(f"| {iso} | {fn_s} | {authority[:48]} |")
    L.append("")

    L.append("## Per-corridor form counts\n")
    L.append("| corridor | distinct forms |\n|---|---|")
    for iso in sorted(per_corridor):
        L.append(f"| {iso} | {len(per_corridor[iso])} |")
    L.append("")

    L.append("## Next actions\n")
    L.append("1. Pick a coded-PDF candidate, fetch it in a browser, and run the AcroForm field-count check. "
             "If fillable, re-seed `form_field_mappings` for it against the real field names (as #2286 did for FR) "
             "and upload the PDF to the `form-templates` bucket.\n")
    L.append("2. Portal/online forms need the data-sheet path (System A / `render_data_sheet`), not AcroForm fill — "
             "the harvested corridor-content already populates that read-only sheet.\n")
    return "\n".join(L) + "\n"


def main() -> None:
    report = build_report()
    if "--write" in sys.argv:
        REPORT.write_text(report, encoding="utf-8")
        print(f"WROTE {REPORT.relative_to(ROOT)}")
    else:
        print(report)


if __name__ == "__main__":
    main()
