#!/usr/bin/env python3
"""
Generate SQL seed file for country_resource_sections from Python defaults.

Run: python3 scripts/generate_country_resources_seed.py

Output: supabase/seeds/country_resources.sql

This keeps country_resources.py as the single source of truth. When you update
content there, re-run this script and commit the updated SQL. The seed runs
automatically on `supabase db reset` (see supabase/config.toml).
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from backend.services.country_resources import (
    RESOURCE_SECTIONS,
    SECTION_LABELS,
    get_default_section_content,
)


def escape_sql_string(s: str) -> str:
    """Escape single quotes for SQL string literals."""
    return s.replace("'", "''")


def main() -> int:
    out_path = Path(__file__).resolve().parent.parent / "supabase" / "seeds" / "country_resources.sql"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    inserts: list[str] = []
    inserts.append("-- Country resource sections seed (generated by scripts/generate_country_resources_seed.py)")
    inserts.append("-- Source: backend/services/country_resources.py")
    inserts.append("")
    inserts.append("-- Clear existing country-level content so re-runs are idempotent")
    inserts.append("DELETE FROM public.country_resource_sections WHERE country_code IN ('NO','SG','US') AND (city IS NULL OR city = '');")
    inserts.append("")
    inserts.append("INSERT INTO public.country_resource_sections (country_code, city, section_key, title, content_json, sort_order)")
    inserts.append("VALUES")

    rows: list[str] = []
    countries = [
        ("NO", ""),
        ("SG", ""),
        ("US", ""),
    ]

    for country_code, city in countries:
        for i, section_key in enumerate(RESOURCE_SECTIONS):
            content = get_default_section_content(country_code, city, section_key)
            if not content or content == {"overview": ""}:
                continue
            title = SECTION_LABELS.get(section_key, section_key.replace("_", " ").title())
            content_json = json.dumps(content, ensure_ascii=False)
            content_escaped = escape_sql_string(content_json)
            city_val = f"'{escape_sql_string(city)}'" if city else "NULL"
            rows.append(f"  ('{country_code}', {city_val}, '{section_key}', '{escape_sql_string(title)}', '{content_escaped}'::jsonb, {i})")

    inserts.append(",\n".join(rows))
    inserts.append(";")

    sql = "\n".join(inserts)
    out_path.write_text(sql, encoding="utf-8")
    print(f"Wrote {out_path} ({len(rows)} rows)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
