-- [P2-5] policy_conflicts table
-- Stores conflict reports generated by the conflict_detector.ts engine.
-- A category cannot be published if it has unresolved high-severity conflicts.

begin;

create table if not exists public.policy_conflicts (
  id uuid primary key default gen_random_uuid(),

  -- Which snapshot triggered this conflict detection run
  snapshot_id uuid references public.policy_knowledge_snapshots (id) on delete cascade,

  -- Conflict metadata
  conflict_type text not null
    check (conflict_type in ('intra_document', 'inter_document', 'version_conflict')),
  category_code text not null,
  tier text,

  -- The two conflicting values (JSON blobs matching ConflictValue schema)
  value_a jsonb not null default '{}'::jsonb,
  value_b jsonb not null default '{}'::jsonb,

  -- Severity: 'high' blocks publication; 'medium' flags but does not block
  severity text not null
    check (severity in ('high', 'medium')),

  -- Resolution state
  status text not null default 'unresolved'
    check (status in ('unresolved', 'resolved', 'dismissed')),
  resolved_by text,                       -- user id of the HR who resolved it
  resolved_at timestamptz,
  resolution_notes text,

  -- Timestamps
  detected_at timestamptz not null default now(),
  created_at  timestamptz not null default now()
);

-- Lookup indexes
create index if not exists idx_policy_conflicts_snapshot
  on public.policy_conflicts (snapshot_id);

create index if not exists idx_policy_conflicts_category
  on public.policy_conflicts (category_code, tier);

create index if not exists idx_policy_conflicts_status
  on public.policy_conflicts (status, severity);

-- ---------------------------------------------------------------------------
-- RLS: HR users can read/update conflicts for their company's snapshots
-- ---------------------------------------------------------------------------

alter table public.policy_conflicts enable row level security;

drop policy if exists policy_conflicts_hr on public.policy_conflicts;
create policy policy_conflicts_hr on public.policy_conflicts
  for all to authenticated
  using (
    exists (
      select 1 from public.policy_knowledge_snapshots s
      join public.profiles p on p.company_id = s.company_id
      where s.id = policy_conflicts.snapshot_id
        and (p.id = auth.uid() or p.role = 'ADMIN')
    )
  )
  with check (
    exists (
      select 1 from public.policy_knowledge_snapshots s
      join public.profiles p on p.company_id = s.company_id
      where s.id = policy_conflicts.snapshot_id
        and (p.id = auth.uid() or p.role = 'ADMIN')
    )
  );

commit;
