-- ============================================================================
-- IE-P0 (destination Ireland) re-source gap-fill -- 3 candidate records.
--
-- Source of truth: docs/imports/ie-p0-resource-gapfill-2026-09-09/src/ie-p0-resource-gapfill.ndjson
--   sha256 a0062466ff5350f5fca53620a5e8da72be778b31644803ca75e3730ebe7fe7f7
-- GENERATED by docs/imports/ie-p0-resource-gapfill-2026-09-09/gen_load.py -- regenerate, do not hand-edit.
--
-- These fill three gaps left open by the 2026-08-31 IE-P0 sweep, each sourced to a
-- verbatim quote from an official Irish source (revenue.ie, citizensinformation.ie).
-- They are NET-NEW ids (no collision with the 145 existing ie_ facts in prod).
--
-- CANDIDATES ONLY. review_status='pending' is EXPLICIT (the column defaults to
-- 'approved' and requirements_builder serves only approved rows, so a plain INSERT
-- would publish unreviewed facts). verification_status='representative' -- NOTHING is
-- verified. A fact reaches a customer only after a human approves it.
--
-- Idempotent: ON CONFLICT (id) DO NOTHING. Re-running never changes an existing row,
-- so a reviewer's later approval/rejection is never overwritten.
-- ============================================================================

INSERT INTO public.requirement_items
    (id, country_code, purpose, pillar, title, description, severity, owner, required_fields_json, citations_json, applies_to_nationality_classes_json, non_obvious, timing, verification_status, review_status, last_verified_at)
VALUES
    (
     'ie_timeline_emergency_tax_refund_via_payroll',
     'IRELAND',
     'employment',
     'TIMELINE',
     'Overpaid emergency tax is refunded automatically through payroll once Revenue issues the RPN',
     'Once your first job is registered with Revenue and your employer receives a cumulative Revenue Payroll Notification (RPN), the Income Tax and USC you overpaid on Emergency Tax are refunded through your wages - you do not make a separate claim to Revenue while you remain employed. Your employer recalculates the correct tax due from the start of the tax year (January) and pays the refund on your next pay day; the date the employer receives the RPN determines which pay day carries it.

Why this is easy to miss: new arrivals often assume they must reclaim emergency tax from Revenue directly, but while employed the refund comes back automatically through payroll once the RPN is in place.',
     'INFO',
     'EMPLOYEE',
     '[]',
     '[{"url": "https://www.revenue.ie/en/jobs-and-pensions/emergency-tax/get-refund-emergency-tax.aspx", "source_name": "Revenue (Office of the Revenue Commissioners) - How to get a refund of Emergency Tax", "topic_key": "emergency_tax_refund", "domain_area": "tax", "source_tier": "official", "evidence_quote": "Your employer will refund any Income Tax and Universal Social Charge (USC) that you have overpaid on your next pay day.", "added_date": "2026-09-09"}]',
     NULL,
     TRUE,
     'Refunded on the next pay day after your employer receives a cumulative RPN - no separate Revenue claim needed while employed',
     'representative',
     'pending',
     NOW()
    ),
    (
     'ie_timeline_myaccount_password_by_post',
     'IRELAND',
     'employment',
     'TIMELINE',
     'A new arrival''s Revenue myAccount password is usually posted, delaying first-job registration',
     'Revenue issues an instant myAccount temporary password (by text or email) only if you can immediately verify two of: an Irish driving licence number, payslip information, or an Income Tax Notice of Assessment. A newly arrived employee typically has none of these, so the temporary password is issued by standard post (valid for 21 days from the date of the letter). Because first-job registration on myAccount depends on this access, the postal delay can push registration past the first pay day - which is what puts a new employee on Emergency Tax. A verified MyGovID / Public Services Card gives immediate access and avoids the wait.

Why this is easy to miss: the ''instant'' myAccount path silently assumes Irish-issued ID or an existing Revenue tax record, which a first-week arrival does not have.',
     'WARN',
     'EMPLOYEE',
     '[]',
     '[{"url": "https://www.revenue.ie/en/online-services/services/myaccount/help-guides/registering.aspx", "source_name": "Revenue (Office of the Revenue Commissioners) - Registering for myAccount", "topic_key": "myaccount_registration", "domain_area": "tax", "source_tier": "official", "evidence_quote": "Where it is not possible to verify this information immediately, the temporary password will be issued to you by post.", "added_date": "2026-09-09"}]',
     NULL,
     TRUE,
     'For new arrivals without Irish ID/payslip the password comes by standard post (21-day validity) - allow for the mailing delay before your first payroll',
     'representative',
     'pending',
     NOW()
    ),
    (
     'ie_medical_card_ordinarily_resident_requirement',
     'IRELAND',
     'employment',
     'HEALTHCARE',
     'A medical card requires being ''ordinarily resident'' - living in Ireland and intending to stay at least one year',
     'Eligibility for a medical card is not only about income: you must also be ''ordinarily resident'' in Ireland, meaning you are living here and intend to live here for at least one year, and the HSE may look for evidence that you are legally entitled to live here for at least a year. A newly arrived employee who cannot yet demonstrate a one-year intention or entitlement may not qualify at the outset, so interim private cover may be needed to bridge the gap until the residency test is met.

Why this is easy to miss: the residency gate is separate from, and additional to, the income means test, so an applicant who passes on income can still be refused on residency in their first months.',
     'WARN',
     'EMPLOYEE',
     '[]',
     '[{"url": "https://www.citizensinformation.ie/en/health/medical-cards-and-gp-visit-cards/medical-card/", "source_name": "Citizens Information (Citizens Information Board) - Medical cards", "topic_key": "medical_card_residency", "domain_area": "healthcare", "source_tier": "official", "evidence_quote": "If you are ''ordinarily resident'' in Ireland you can apply for a medical card. This means that you are living in Ireland and intend to live here for at least one year.", "added_date": "2026-09-09"}]',
     NULL,
     TRUE,
     'Assessed at application; new arrivals may not meet the >=1-year ''ordinarily resident'' test immediately - plan interim cover',
     'representative',
     'pending',
     NOW()
    )
ON CONFLICT (id) DO NOTHING;
