-- Ledger reconciliation (prod-as-oracle). This IE-P0 migration was applied to prod
-- out-of-band and recorded in supabase_migrations.schema_migrations at version 20261131000000
-- (name: ie_p0_resource_updates) with NO matching repo file, failing the Migration ledger
-- drift check on every migration PR. The SQL below is reproduced verbatim from that
-- ledger row's stored statements. Idempotent (ON CONFLICT / keyed UPDATEs). Do NOT
-- `supabase db push`; this file exists only so repo and ledger agree.

-- ============================================================================
-- Ireland P0 re-source updates (Otto batch 2) — reconciled migration.
-- ============================================================================
-- Ireland P0 re-source: 10 held facts -> official/primary citations (Otto batch 2).
-- Otto also corrected claims (Revolut SEPA direction; Ulster/KBC timing). UPDATE by id=fact_uid;
-- review_status unchanged (pending -> now approvable). Human-applied; never db push.

UPDATE public.requirement_items SET description='Revolut migrated Irish customers from Lithuanian (LT) IBANs to Irish (IE) IBANs in 2023, reducing IBAN discrimination risk for salary receipt. Revolut''s Irish branch launched in April 2023 and over two million customers were migrated within six weeks.', citations_json='[{"url": "https://www.revolut.com/en-IE/news/revolut_business_launches_local_ibans_for_corporate_clients_in_ireland/", "source_name": "revolut.com", "topic_key": "fintech_bridge", "domain_area": "banking", "source_tier": "primary", "evidence_quote": "With the launch of Revolut Bank''s Irish branch in March, Revolut began rolling out IBANs to its retail customers in Ireland. In just six weeks, Revolut has successfully migrated over two million of its Irish customers.", "added_date": "2026-08-31", "resourced": true}]', timing='Phased migration began March/April 2023; retail migration completed by May 2023', last_verified_at=NOW() WHERE id='ie_fintech_bridge_revolut_irish_iban_2023' AND country_code='IRELAND';

UPDATE public.requirement_items SET description='After Ulster Bank and KBC Bank Ireland announced their intention to exit the Irish retail banking market in 2021 and subsequently withdrew, the number of domestic retail banks reduced from five to three (AIB, Bank of Ireland, Permanent TSB), concentrating the market significantly and making fintechs a de facto bridge account for new arrivals.', citations_json='[{"url": "https://www.centralbank.ie/statistics/data-and-analysis/credit-and-banking-statistics/account-migration-statistics", "source_name": "centralbank.ie", "topic_key": "fintech_bridge", "domain_area": "banking", "source_tier": "official", "evidence_quote": "Ulster Bank and KBC Bank announced their intentions to leave the Irish market in 2021 ... the three largest remaining retail banks; Allied Irish Banks, Bank of Ireland, and Permanent TSB.", "added_date": "2026-08-31", "resourced": true}]', timing='Ulster Bank branches closed April 2023; KBC final closure August 2023', last_verified_at=NOW() WHERE id='ie_fintech_bridge_revolut_competition_context' AND country_code='IRELAND';

UPDATE public.requirement_items SET description='IBAN discrimination — refusing a payment or direct debit mandate because the IBAN is from a different EU member state — is prohibited under EU SEPA Regulation No 260/2012, Article 9, which requires that neither a payer nor a payee may specify the Member State in which a payment account must be located.', citations_json='[{"url": "https://www.centralbank.ie/consumer-hub/explainers/what-is-iban-discrimination-and-what-can-i-do-about-it", "source_name": "centralbank.ie", "topic_key": "fintech_bridge", "domain_area": "banking", "source_tier": "official", "evidence_quote": "IBAN discrimination is where an employer or company, such as a utility company, refuses to accept your SEPA IBAN for euro payments or direct debits.", "added_date": "2026-08-31", "resourced": true}]', timing=NULL, last_verified_at=NOW() WHERE id='ie_fintech_bridge_revolut_iban_discrimination_context' AND country_code='IRELAND';

UPDATE public.requirement_items SET description='Revolut Standard accounts in Ireland offer no overdraft facility — transactions that would bring the balance below zero are declined. The Standard plan also provides fee-free ATM cash withdrawals only up to €200 per rolling month or 5 withdrawals (whichever comes first), after which a 2% fee (minimum €1) applies per transaction.', citations_json='[{"url": "https://help.revolut.com/en-IE/help/credit-products/question-credit-overdraft-availability/", "source_name": "help.revolut.com", "topic_key": "fintech_bridge", "domain_area": "banking", "source_tier": "primary", "evidence_quote": "We currently don''t offer overdraft services in IE. This means that if you attempt to make a transaction that would bring your account balance below zero, the transaction will be declined.", "added_date": "2026-08-31", "resourced": true}]', timing=NULL, last_verified_at=NOW() WHERE id='ie_fintech_bridge_revolut_no_overdraft_cash_limit' AND country_code='IRELAND';

UPDATE public.requirement_items SET description='Revolut supports outbound SEPA Direct Debits on personal Irish accounts, allowing users to pay bills such as utilities by direct debit. Revolut does not support inbound SEPA Direct Debits (i.e. acting as a creditor collecting mandates). If a biller refuses to accept a Revolut IE IBAN for an outbound direct debit, this constitutes IBAN discrimination and is prohibited under EU SEPA Regulation No 260/2012, Article 9.', citations_json='[{"url": "https://help.revolut.com/en-IE/help/transfers/outbound-transfers/how-to-send-money-to-another-bank/paying-via-direct-debit/setting-up-a-direct-debit/", "source_name": "help.revolut.com", "topic_key": "fintech_bridge", "domain_area": "banking", "source_tier": "primary", "evidence_quote": "Only SEPA Direct Debits in euros are available. Revolut doesn''t charge any fees for setting up or processing Direct Debits, and you can set up as many different Direct Debits as you want with no imposed limits.", "added_date": "2026-08-31", "resourced": true}]', timing=NULL, last_verified_at=NOW() WHERE id='ie_fintech_bridge_revolut_sepa_direct_debit' AND country_code='IRELAND';

UPDATE public.requirement_items SET description='Irish IBANs are 22 characters long, consisting of the country code IE, 2 numeric check digits, a 4-character alphabetic bank identifier (BBAN prefix), a 6-digit sort code, and an 8-digit account number (IE + 2 check digits + 4-character bank code + 6-digit sort code + 8-digit account number = 22 characters total).', citations_json='[{"url": "https://bpfi.ie/customer-assist/personal-customers/bic-iban-information/", "source_name": "bpfi.ie", "topic_key": "iban_sepa", "domain_area": "banking", "source_tier": "semi_official", "evidence_quote": "in Ireland, the standard length of an IBAN is 22 characters.", "added_date": "2026-08-31", "resourced": true}]', timing=NULL, last_verified_at=NOW() WHERE id='ie_iban_sepa_irish_iban_structure' AND country_code='IRELAND';

UPDATE public.requirement_items SET description='Ulster Bank Ireland and KBC Bank Ireland announced their exit from the Irish retail banking market in 2021. Ulster Bank''s branches closed in April 2023 and KBC Bank Ireland''s final closure was August 2023, reducing full-service domestic retail banks from five to three (AIB, Bank of Ireland, Permanent TSB). Note: the claim that Ulster Bank completed its exit ''by early 2024'' should be amended — the operational exit was substantially complete by mid-2023.', citations_json='[{"url": "https://www.centralbank.ie/statistics/data-and-analysis/credit-and-banking-statistics/account-migration-statistics", "source_name": "centralbank.ie", "topic_key": "resident_account_opening", "domain_area": "banking", "source_tier": "official", "evidence_quote": "Ulster Bank and KBC Bank announced their intentions to leave the Irish market in 2021 ... the three largest remaining retail banks; Allied Irish Banks, Bank of Ireland, and Permanent TSB.", "added_date": "2026-08-31", "resourced": true}]', timing='Ulster Bank branches closed April 2023; KBC Bank Ireland final hub closed 31 August 2023; by end-June 2023 96% of accounts at both banks were closed or inactive', last_verified_at=NOW() WHERE id='ie_resident_account_opening_ulster_kbc_market_exit' AND country_code='IRELAND';

UPDATE public.requirement_items SET description='Ireland has no operational State-backed tenancy deposit protection scheme; deposits are held by the landlord or their agent and are not ring-fenced in a government account. The Residential Tenancies (Amendment) Act 2015 provided for an RTB-managed scheme but those provisions have never been commenced. Tenants must rely on the RTB dispute process to recover disputed deposits.', citations_json='[{"url": "https://threshold.ie/support-a-deposit-protection-scheme-support-renters/", "source_name": "threshold.ie", "topic_key": "lease_deposit_rtb", "domain_area": "housing", "source_tier": "semi_official", "evidence_quote": "When you give your landlord a deposit, there''s no guarantee when, or even if, you''ll get it back.", "added_date": "2026-08-31", "resourced": true}]', timing=NULL, last_verified_at=NOW() WHERE id='ie_lease_deposit_rtb_no_state_scheme' AND country_code='IRELAND';

UPDATE public.requirement_items SET description='Deposit-related disputes are among the most common dispute types adjudicated by the Residential Tenancies Board (RTB), consistently appearing in the top dispute categories in RTB annual reports and quarterly updates.', citations_json='[{"url": "https://rtb.ie/disputes/", "source_name": "rtb.ie", "topic_key": "rental_market", "domain_area": "housing", "source_tier": "official", "evidence_quote": "The most common disputes brought to the Residential Tenancies Board (RTB) are validity of a notice of termination, unlawful termination of a tenancy, rent arrears, deposit retention and rent arrears with overholding.", "added_date": "2026-08-31", "resourced": true}]', timing=NULL, last_verified_at=NOW() WHERE id='ie_rental_market_deposit_dispute_volume' AND country_code='IRELAND';

UPDATE public.requirement_items SET description='Tenants who win RTB adjudications for deposit retention typically receive a Determination Order requiring repayment of the deposit; however, enforcement of RTB Determination Orders against non-compliant landlords requires a further step of applying to the District Court (not the Circuit Court) for enforcement proceedings, with the RTB able to provide legal assistance and template court documents to eligible parties.', citations_json='[{"url": "https://rtb.ie/disputes/enforcement-of-determination-orders/", "source_name": "rtb.ie", "topic_key": "tenant_rights", "domain_area": "housing", "source_tier": "official", "evidence_quote": "If you want to bring your own District Court enforcement case, you can ask the RTB for support. We will give you copies of all relevant documents from your dispute case (usually within 7 days of getting your request).", "added_date": "2026-08-31", "resourced": true}]', timing=NULL, last_verified_at=NOW() WHERE id='ie_tenant_rights_deposit_dispute_outcome' AND country_code='IRELAND';
