-- ============================================================
-- [AIQ-806 / P3-04f] Backfill source_pages tiers from corridor corpus
-- Date: 2026-06-29
--
-- source_pages was seed-bootstrapped from form_templates at the default
-- tier '1', so the roadmap ConfidenceBadge resolved to a uniform level and
-- most official URLs had no row. This migration upserts one row per distinct
-- corpus source URL with its REAL trust tier (source_tier 1/2/3) so confidence
-- resolves to honest HIGH/MEDIUM/LOW on the live /roadmap/tracks path.
--
-- Idempotent + replay-safe: ON CONFLICT (url) overwrites tier (corpus is
-- authoritative) but preserves any real crawler last_fetched_at via COALESCE.
-- No new table → no RLS gate (source_pages already has RLS + REVOKE anon).
-- Generated by backend/scripts/backfill_source_pages_from_corpus.py.
-- ============================================================

-- AIQ-806 / P3-04f · Backfill public.source_pages tiers from corridor corpus
-- Generated by backend/scripts/backfill_source_pages_from_corpus.py — do not hand-edit.
-- 31 distinct official source URLs across 6 corpus file(s).

INSERT INTO public.source_pages (url, tier, last_fetched_at) VALUES
  ('https://administration-etrangers-en-france.interieur.gouv.fr/', '1', '2026-06-04'::timestamptz),
  ('https://aima.gov.pt/pt', '1', '2026-06-04'::timestamptz),
  ('https://aima.gov.pt/pt/viver/autorizacao-de-residencia-regime-e-requisitos-gerais-art-o-77-o-n-o-1', '1', '2026-06-04'::timestamptz),
  ('https://anabin.kmk.org/anabin/hochschulen.html', '1', '2026-06-04'::timestamptz),
  ('https://france-visas.gouv.fr/en/activite-salariee', '1', '2026-06-04'::timestamptz),
  ('https://france-visas.gouv.fr/en/brexit', '1', '2026-06-04'::timestamptz),
  ('https://france-visas.gouv.fr/en/royaume-uni', '1', '2026-06-04'::timestamptz),
  ('https://france-visas.gouv.fr/en/talents-internationaux-et-attractivite-economique', '1', '2026-06-04'::timestamptz),
  ('https://france-visas.gouv.fr/web/france-visas/passeport-talents', '1', '2026-06-04'::timestamptz),
  ('https://ind.nl/en/recognition-as-a-sponsor', '1', '2026-06-29'::timestamptz),
  ('https://ind.nl/en/residence-permits/work/eu-blue-card', '1', '2026-06-29'::timestamptz),
  ('https://ind.nl/en/residence-permits/work/highly-skilled-migrant', '1', '2026-06-29'::timestamptz),
  ('https://vistos.mne.gov.pt/en/national-visas/general-information/deadlines', '1', '2026-06-04'::timestamptz),
  ('https://vistos.mne.gov.pt/en/national-visas/general-information/type-of-visa', '1', '2026-06-04'::timestamptz),
  ('https://vistos.mne.gov.pt/en/national-visas/necessary-documentation/cplp-en', '1', '2026-06-04'::timestamptz),
  ('https://vistos.mne.gov.pt/en/national-visas/necessary-documentation/residency', '1', '2026-06-04'::timestamptz),
  ('https://www.auswaertiges-amt.de/en/visa-service/buergerservice/faq/02a-what-is-the-blue-card/606754', '1', '2026-06-04'::timestamptz),
  ('https://www.bamf.de/EN/Themen/MigrationAufenthalt/ZuwandererDrittstaaten/Migrathek/BlaueKarteEU/blauekarteeu-node.html', '1', '2026-06-04'::timestamptz),
  ('https://www.belastingdienst.nl/wps/wcm/connect/en/individuals/individuals', '1', '2026-06-29'::timestamptz),
  ('https://www.france-visas.gouv.fr/en/visa-de-long-sejour', '1', '2026-06-04'::timestamptz),
  ('https://www.gov.uk/get-document-legalised', '1', '2026-06-04'::timestamptz),
  ('https://www.government.nl/topics/personal-data/citizen-service-number-bsn', '1', '2026-06-29'::timestamptz),
  ('https://www.international.gc.ca/gac-amc/about-a_propos/services/authentication-authentification/apostille-convention.aspx?lang=eng', '1', '2026-06-04'::timestamptz),
  ('https://www.international.gc.ca/gac-amc/about-a_propos/services/authentication-authentification/faq.aspx?lang=eng', '1', '2026-06-04'::timestamptz),
  ('https://www.make-it-in-germany.com/en/visa-residence/skilled-immigration-act', '2', '2026-06-04'::timestamptz),
  ('https://www.make-it-in-germany.com/en/visa-residence/types/eu-blue-card', '2', '2026-06-04'::timestamptz),
  ('https://www.make-it-in-germany.com/en/working-in-germany/recognition/foreign-academic-qualifications', '2', '2026-06-04'::timestamptz),
  ('https://www.service-public.fr/particuliers/vosdroits/F16162?lang=en', '1', '2026-06-04'::timestamptz),
  ('https://www.service-public.fr/particuliers/vosdroits/F16922', '1', '2026-06-04'::timestamptz),
  ('https://www.service-public.fr/particuliers/vosdroits/F35495/3_1_1_5_0_1?lang=en', '1', '2026-06-04'::timestamptz),
  ('https://www.service-public.fr/particuliers/vosdroits/F35602/1_0?lang=en', '1', '2026-06-04'::timestamptz)
ON CONFLICT (url) DO UPDATE SET
    tier = EXCLUDED.tier,
    last_fetched_at = COALESCE(public.source_pages.last_fetched_at, EXCLUDED.last_fetched_at),
    updated_at = now();
