-- Migration: policy_calibration_alerts
-- P5-7: Policy gap detection & calibration alerts for HR
--
-- Creates:
--   policy_calibration_alerts — one row per detected gap (org × category × tier_name)
--                               generated by the gap-detection-weekly Edge Function
--
-- Design:
--   • Immutable once created; HR dismisses via dismissed_at (soft-dismiss).
--   • Deduplication is handled by the Edge Function (no duplicate within 7 days
--     for the same org + category + tier_name combination).
--   • tier_name is nullable — employees without an assigned tier are grouped
--     together as NULL.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.policy_calibration_alerts (
    id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id  UUID        NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    category         TEXT        NOT NULL CHECK (char_length(category) BETWEEN 1 AND 100),
    -- tier_name from employee_tiers.tier_name; NULL = employee has no tier assigned
    tier_name        TEXT,
    exception_count  INT         NOT NULL CHECK (exception_count >= 1),
    avg_excess_pct   NUMERIC(7,4) NOT NULL,   -- e.g. 0.1500 = 15 %
    alert_message    TEXT        NOT NULL,
    dismissed_at     TIMESTAMPTZ,
    dismissed_by     UUID        REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Fast lookup for the HR dashboard banner (undismissed alerts for an org)
CREATE INDEX IF NOT EXISTS idx_policy_calibration_alerts_org_active
    ON public.policy_calibration_alerts (organization_id, created_at DESC)
    WHERE dismissed_at IS NULL;

-- Used by the Edge Function dedup check
CREATE INDEX IF NOT EXISTS idx_policy_calibration_alerts_dedup
    ON public.policy_calibration_alerts (organization_id, category, tier_name, created_at DESC);

-- ---------------------------------------------------------------------------
-- Row-Level Security
-- ---------------------------------------------------------------------------
ALTER TABLE public.policy_calibration_alerts ENABLE ROW LEVEL SECURITY;

-- HR/Admin in same company can read their org's alerts
DROP POLICY IF EXISTS "hr_read_calibration_alerts" ON public.policy_calibration_alerts;
CREATE POLICY "hr_read_calibration_alerts"
    ON public.policy_calibration_alerts FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles p
            WHERE p.id::uuid = auth.uid()
              AND p.company_id = organization_id
              AND p.role IN ('hr', 'admin', 'HR', 'ADMIN')
        )
    );

-- HR/Admin in same company can dismiss (UPDATE dismissed_at only)
DROP POLICY IF EXISTS "hr_dismiss_calibration_alerts" ON public.policy_calibration_alerts;
CREATE POLICY "hr_dismiss_calibration_alerts"
    ON public.policy_calibration_alerts FOR UPDATE
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles p
            WHERE p.id::uuid = auth.uid()
              AND p.company_id = organization_id
              AND p.role IN ('hr', 'admin', 'HR', 'ADMIN')
        )
    );

-- Service role (Edge Function) can insert
DROP POLICY IF EXISTS "service_insert_calibration_alerts" ON public.policy_calibration_alerts;
CREATE POLICY "service_insert_calibration_alerts"
    ON public.policy_calibration_alerts FOR INSERT
    WITH CHECK (TRUE);
-- Note: the Edge Function runs with service_role key which bypasses RLS anyway;
-- this policy is a no-op safety net for future direct inserts.
