/**
 * Draft vs Live diff for the canonical (document-normalized) policy
 * pipeline — sibling of PolicyDiffView (matrix). Rendered below the
 * matrix diff in Section 4 when the company has a canonical policy.
 *
 * Scope mirrors the backend module (policy_canonical_diff.py): shows
 * changed / added / removed rule + exclusion rows. No per-row revert
 * yet — canonical rules are usually regenerated by re-normalizing a
 * document, so a per-row revert has fuzzier semantics and deserves
 * its own product round. The entire-draft re-normalize still lives
 * in the Detailed review drawer.
 *
 * When the company has no canonical policy at all (matrix-only
 * deployment), the server returns has_policy=false and this component
 * renders a neutral empty state instead of taking up page real estate.
 */
import React, { useCallback, useEffect, useState } from 'react';
import { Alert, Badge, Button, Card } from '../../components/antigravity';
import { companyPolicyAPI } from '../../api/client';
import {
  CollapsibleCategory,
  groupByCategory,
  shouldDefaultOpen,
} from './diffCategoryGrouping';

// --- Types -----------------------------------------------------------------

type RuleRow = {
  benefit_key?: string;
  benefit_category?: string;
  calc_type?: string | null;
  amount_value?: number | null;
  amount_unit?: string | null;
  currency?: string | null;
  frequency?: string | null;
  description?: string | null;
  review_status?: string | null;
};

type ExclusionRow = {
  benefit_key?: string | null;
  domain?: string;
  description?: string | null;
  review_status?: string | null;
};

type ChangedRule = {
  before: RuleRow;
  after: RuleRow;
  changed_fields: string[];
};

type ChangedExclusion = {
  before: ExclusionRow;
  after: ExclusionRow;
  changed_fields: string[];
};

type Summary = {
  added: number;
  removed: number;
  changed: number;
  unchanged: number;
};

type Payload = {
  has_policy?: boolean;
  live?: { version?: { version_number?: number; status?: string } | null };
  draft?: { version?: { version_number?: number; status?: string } | null };
  diff?: {
    rules: {
      added: RuleRow[];
      removed: RuleRow[];
      changed: ChangedRule[];
      unchanged_count: number;
    };
    exclusions: {
      added: ExclusionRow[];
      removed: ExclusionRow[];
      changed: ChangedExclusion[];
      unchanged_count: number;
    };
    summary: { rules: Summary; exclusions: Summary };
  };
};

type Props = {
  adminCompanyId?: string | null;
  refreshTrigger?: number;
};

// --- Helpers ---------------------------------------------------------------

const RULE_FIELD_LABELS: Record<string, string> = {
  benefit_category: 'Category',
  amount_value: 'Amount',
  currency: 'Currency',
  description: 'Description',
  raw_text: 'Source wording',
  review_status: 'Review status',
  confidence: 'Confidence',
  metadata_json: 'Metadata',
};

const EXCL_FIELD_LABELS: Record<string, string> = {
  description: 'Description',
  raw_text: 'Source wording',
  review_status: 'Review status',
  confidence: 'Confidence',
};

function ruleLabel(r: RuleRow): string {
  return r.benefit_key?.trim() || 'Unnamed rule';
}

function ruleCap(r: RuleRow): string {
  if (r.amount_value == null) return '—';
  const cur = r.currency ? `${r.currency} ` : '';
  return `${cur}${r.amount_value}${r.frequency ? ` · ${r.frequency}` : ''}`;
}

function exclusionLabel(e: ExclusionRow): string {
  return (e.benefit_key?.trim() || e.domain?.trim() || 'Exclusion') + '';
}

// --- Section renderers -----------------------------------------------------

const SummaryBadges: React.FC<{ summary: Summary; label: string }> = ({ summary, label }) => {
  const totalChanges = summary.added + summary.removed + summary.changed;
  return (
    <div className="flex flex-wrap items-center gap-2">
      <span className="text-sm font-medium text-[#0b2b43]">{label}:</span>
      <Badge variant="success" size="sm">+{summary.added}</Badge>
      <Badge variant="warning" size="sm">~{summary.changed}</Badge>
      <Badge variant="error" size="sm">−{summary.removed}</Badge>
      <Badge variant="neutral" size="sm">{summary.unchanged} unchanged</Badge>
      {totalChanges === 0 && (
        <span className="text-xs text-emerald-700">No changes</span>
      )}
    </div>
  );
};

const AddedRule: React.FC<{ r: RuleRow }> = ({ r }) => (
  <li
    className="border-l-4 border-emerald-500 bg-emerald-50/60 px-3 py-2 rounded-r-md"
    data-testid="canonical-diff-rule-added"
  >
    <div className="text-xs font-semibold text-emerald-800 uppercase tracking-wide">New</div>
    <div className="font-medium text-[#0b2b43]">{ruleLabel(r)}</div>
    <div className="text-sm text-slate-700 mt-0.5">{ruleCap(r)}</div>
    {r.description && <div className="text-xs text-slate-600 mt-1">{r.description}</div>}
  </li>
);

const RemovedRule: React.FC<{ r: RuleRow }> = ({ r }) => (
  <li
    className="border-l-4 border-red-500 bg-red-50/60 px-3 py-2 rounded-r-md"
    data-testid="canonical-diff-rule-removed"
  >
    <div className="text-xs font-semibold text-red-800 uppercase tracking-wide">Removed</div>
    <div className="font-medium text-[#0b2b43] line-through decoration-red-400">
      {ruleLabel(r)}
    </div>
    <div className="text-sm text-slate-700 mt-0.5">Was: {ruleCap(r)}</div>
  </li>
);

const ChangedRuleRow: React.FC<{ entry: ChangedRule }> = ({ entry }) => {
  const { before, after, changed_fields } = entry;
  return (
    <li
      className="border-l-4 border-amber-500 bg-amber-50/60 px-3 py-2 rounded-r-md"
      data-testid="canonical-diff-rule-changed"
    >
      <div className="text-xs font-semibold text-amber-800 uppercase tracking-wide">Changed</div>
      <div className="font-medium text-[#0b2b43]">{ruleLabel(after)}</div>
      <ul className="mt-2 space-y-1">
        {changed_fields.map((f) => {
          const lhs = (before as Record<string, unknown>)[f];
          const rhs = (after as Record<string, unknown>)[f];
          return (
            <li key={f} className="text-sm">
              <span className="text-xs font-medium text-slate-600">
                {RULE_FIELD_LABELS[f] ?? f}:
              </span>{' '}
              <span className="text-red-700 line-through decoration-red-300">
                {String(lhs ?? '—')}
              </span>{' '}
              <span className="text-slate-500">→</span>{' '}
              <span className="text-emerald-800 font-medium">
                {String(rhs ?? '—')}
              </span>
            </li>
          );
        })}
      </ul>
    </li>
  );
};

const AddedExclusion: React.FC<{ e: ExclusionRow }> = ({ e }) => (
  <li className="border-l-4 border-emerald-500 bg-emerald-50/60 px-3 py-2 rounded-r-md">
    <div className="text-xs font-semibold text-emerald-800 uppercase tracking-wide">New exclusion</div>
    <div className="font-medium text-[#0b2b43]">{exclusionLabel(e)}</div>
    {e.description && <div className="text-xs text-slate-700 mt-0.5">{e.description}</div>}
  </li>
);

const RemovedExclusion: React.FC<{ e: ExclusionRow }> = ({ e }) => (
  <li className="border-l-4 border-red-500 bg-red-50/60 px-3 py-2 rounded-r-md">
    <div className="text-xs font-semibold text-red-800 uppercase tracking-wide">Removed exclusion</div>
    <div className="font-medium text-[#0b2b43] line-through decoration-red-400">
      {exclusionLabel(e)}
    </div>
  </li>
);

const ChangedExclusionRow: React.FC<{ entry: ChangedExclusion }> = ({ entry }) => (
  <li className="border-l-4 border-amber-500 bg-amber-50/60 px-3 py-2 rounded-r-md">
    <div className="text-xs font-semibold text-amber-800 uppercase tracking-wide">Changed exclusion</div>
    <div className="font-medium text-[#0b2b43]">{exclusionLabel(entry.after)}</div>
    <ul className="mt-2 space-y-1">
      {entry.changed_fields.map((f) => {
        const lhs = (entry.before as Record<string, unknown>)[f];
        const rhs = (entry.after as Record<string, unknown>)[f];
        return (
          <li key={f} className="text-sm">
            <span className="text-xs font-medium text-slate-600">
              {EXCL_FIELD_LABELS[f] ?? f}:
            </span>{' '}
            <span className="text-red-700 line-through decoration-red-300">
              {String(lhs ?? '—')}
            </span>{' '}
            <span className="text-slate-500">→</span>{' '}
            <span className="text-emerald-800 font-medium">
              {String(rhs ?? '—')}
            </span>
          </li>
        );
      })}
    </ul>
  </li>
);

// --- Main component --------------------------------------------------------

export const CanonicalPolicyDiffView: React.FC<Props> = ({
  adminCompanyId,
  refreshTrigger,
}) => {
  const [payload, setPayload] = useState<Payload | null>(null);
  const [loading, setLoading] = useState(true);
  const [err, setErr] = useState<string | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    setErr(null);
    try {
      const res = await companyPolicyAPI.hrCanonicalDiffForCompany(
        adminCompanyId ?? undefined
      );
      setPayload(res);
    } catch (e: unknown) {
      const ax = e as { response?: { data?: { detail?: string | { message?: string } } } };
      const d = ax.response?.data?.detail;
      setErr(
        typeof d === 'string'
          ? d
          : (d && typeof d === 'object' && 'message' in d && (d).message) ||
              'Could not load the document-policy diff.'
      );
    } finally {
      setLoading(false);
    }
  }, [adminCompanyId]);

  useEffect(() => {
    void load();
  }, [load, refreshTrigger]);

  // Empty state: no canonical policy for this company at all.
  if (!loading && payload && payload.has_policy === false) {
    return null;
  }

  if (loading && !payload) {
    return (
      <Card padding="lg">
        <h3 className="text-base font-semibold text-[#0b2b43]">
          Document-normalized policy — Draft vs Live
        </h3>
        <p className="text-sm text-slate-600 mt-2">Loading…</p>
      </Card>
    );
  }

  const diff = payload?.diff;
  const rules = diff?.rules;
  const exclusions = diff?.exclusions;
  const ruleSummary = diff?.summary.rules;
  const exclSummary = diff?.summary.exclusions;
  const hasDraft = Boolean(payload?.draft?.version);
  const hasChanges = Boolean(
    ruleSummary &&
      exclSummary &&
      (ruleSummary.added +
        ruleSummary.removed +
        ruleSummary.changed +
        exclSummary.added +
        exclSummary.removed +
        exclSummary.changed >
        0)
  );

  if (!hasDraft) {
    return (
      <Card padding="lg" className="border-dashed">
        <h3 className="text-base font-semibold text-[#0b2b43]">
          Document-normalized policy — Draft vs Live
        </h3>
        <p className="text-sm text-slate-600 mt-2">
          No draft in progress from a document-normalized policy. When you re-normalize
          an uploaded document, the rule-level changes will preview here.
        </p>
      </Card>
    );
  }

  const liveLabel = payload?.live?.version
    ? `Live v${payload.live.version.version_number ?? '?'}`
    : 'No live version';
  const draftLabel = `Draft v${payload!.draft!.version!.version_number ?? '?'}`;

  return (
    <Card padding="lg" data-testid="canonical-policy-diff">
      <div className="flex items-start justify-between gap-3">
        <div className="min-w-0">
          <h3 className="text-base font-semibold text-[#0b2b43]">
            Document-normalized policy — {draftLabel} vs {liveLabel}
          </h3>
          <p className="text-sm text-slate-600 mt-1">
            Rule-level changes in the normalized policy from your uploaded document.
            Publishing happens in the Detailed review drawer.
          </p>
          <div className="mt-3 flex flex-col gap-1">
            {ruleSummary && <SummaryBadges summary={ruleSummary} label="Benefit rules" />}
            {exclSummary && <SummaryBadges summary={exclSummary} label="Exclusions" />}
          </div>
        </div>
        <Button size="sm" variant="outline" onClick={() => void load()} disabled={loading}>
          {loading ? 'Refreshing…' : 'Refresh'}
        </Button>
      </div>

      {err && (
        <Alert variant="error" className="mt-4">
          {err}
        </Alert>
      )}

      {!hasChanges ? (
        <p className="text-sm text-emerald-800 bg-emerald-50 border border-emerald-200 rounded px-3 py-2 mt-4">
          Draft matches the live version rule-for-rule. Nothing to publish.
        </p>
      ) : (
        <div className="mt-4 space-y-6">
          {rules && rules.changed.length > 0 && (
            <section>
              <h4 className="text-sm font-semibold text-[#0b2b43] mb-2">
                Changed rules ({rules.changed.length})
              </h4>
              <div className="space-y-2">
                {groupByCategory(rules.changed, (e) => e.after.benefit_category).map((g) => (
                  <CollapsibleCategory
                    key={g.key}
                    group={g}
                    accentClassName="border-l-4 border-l-amber-400"
                    defaultOpen={shouldDefaultOpen(rules.changed.length)}
                    testId="canonical-diff-changed-group"
                    renderRow={(entry, i) => <ChangedRuleRow key={`rc-${i}`} entry={entry} />}
                  />
                ))}
              </div>
            </section>
          )}
          {rules && rules.added.length > 0 && (
            <section>
              <h4 className="text-sm font-semibold text-[#0b2b43] mb-2">
                Added rules ({rules.added.length})
              </h4>
              <div className="space-y-2">
                {groupByCategory(rules.added, (r) => r.benefit_category).map((g) => (
                  <CollapsibleCategory
                    key={g.key}
                    group={g}
                    accentClassName="border-l-4 border-l-emerald-400"
                    defaultOpen={shouldDefaultOpen(rules.added.length)}
                    testId="canonical-diff-added-group"
                    renderRow={(r, i) => <AddedRule key={`ra-${i}`} r={r} />}
                  />
                ))}
              </div>
            </section>
          )}
          {rules && rules.removed.length > 0 && (
            <section>
              <h4 className="text-sm font-semibold text-[#0b2b43] mb-2">
                Removed rules ({rules.removed.length})
              </h4>
              <div className="space-y-2">
                {groupByCategory(rules.removed, (r) => r.benefit_category).map((g) => (
                  <CollapsibleCategory
                    key={g.key}
                    group={g}
                    accentClassName="border-l-4 border-l-red-400"
                    defaultOpen={shouldDefaultOpen(rules.removed.length)}
                    testId="canonical-diff-removed-group"
                    renderRow={(r, i) => <RemovedRule key={`rr-${i}`} r={r} />}
                  />
                ))}
              </div>
            </section>
          )}
          {exclusions && exclusions.changed.length > 0 && (
            <section>
              <h4 className="text-sm font-semibold text-[#0b2b43] mb-2">
                Changed exclusions ({exclusions.changed.length})
              </h4>
              <ul className="space-y-2">
                {exclusions.changed.map((entry, i) => (
                  <ChangedExclusionRow key={`ec-${i}`} entry={entry} />
                ))}
              </ul>
            </section>
          )}
          {exclusions && exclusions.added.length > 0 && (
            <section>
              <h4 className="text-sm font-semibold text-[#0b2b43] mb-2">
                Added exclusions ({exclusions.added.length})
              </h4>
              <ul className="space-y-2">
                {exclusions.added.map((e, i) => (
                  <AddedExclusion key={`ea-${i}`} e={e} />
                ))}
              </ul>
            </section>
          )}
          {exclusions && exclusions.removed.length > 0 && (
            <section>
              <h4 className="text-sm font-semibold text-[#0b2b43] mb-2">
                Removed exclusions ({exclusions.removed.length})
              </h4>
              <ul className="space-y-2">
                {exclusions.removed.map((e, i) => (
                  <RemovedExclusion key={`er-${i}`} e={e} />
                ))}
              </ul>
            </section>
          )}
          <p className="text-xs text-slate-500">
            {(rules?.unchanged_count ?? 0) + (exclusions?.unchanged_count ?? 0)} unchanged rows not shown.
          </p>
        </div>
      )}
    </Card>
  );
};
